prometheus_pve_exporter_config: ENC[AES256_GCM,data:CjvoyuR8xyzsRVixtglLr/np8/kMRA0AmFvo64S3qLw7FKi1i27+8EudEYxHE59qsI3Mo2x59Qw2HVnLDYNxDFpplp3zUbM=,iv:zR5umjclnyq8d8bfNmWVST84X+c2jx7zRlBwzxDDHUk=,tag:cOxtRkcwwkORqemL6sDNfg==,type:str]
sops:
    age:
        - recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVHFXVXE5cWdubklGWEVO
            WU9Gc2tpMU1YK2p0T3BSOUZ5VWVhTnFkUlhvCkVJeUR4enVqQjdVZCtXdFc1bDNS
            d1dVaGRtcG0xWkY1ZTR4Zmticm1BVzgKLS0tIFBXY01YRlRpaHFXeE8vWHI1Y1Rk
            SHdJdzkxUHd5TDJQb0JzMXhyVEFGNG8KZk4NBwZAFJvwt4ooVTeshCe0DRnNFuvG
            2XSOCUsuT17sBqKsKJug4rEQ1k/jPDSVTG4asgM18ggQwOTuNEGcXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxs9kx4nezjunv8a7m9cz07vd5843dxx239elz2wt0ms6u5ls97q9ud6k7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZjE3UGlmdHlha2RkT3pt
            eVVWb0V2SmQzSGIzWGlyQ2U1NGwxMlhheEF3CjFrSXBvR2JkeERvSGFOemdoUnJm
            c3FaNHU5QlZUNjB6NjRpOGsydVRpeUEKLS0tIE5jVVZoWHM5UVJjVFl3RzN5V0dR
            Y0FKTXVFM09XZ3l4R0hVeGpiaGhTalkKFpdp43szE53LLkDWk4zNVxya631zgv3T
            4jbl8d0ZYLbuo9k7yGkqetjma073uBFZD3caMIY1fjO+4fb1Q8/bug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age134vfx7ce3z7fpzqpcm4nlwcav0apm00g95nrrgm2y0m8wa7rvy6s765gl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheUhmbFRFU1NpVXZkaG5U
            RlIvMVVhMlhHMzlOUFkybDVSZmtBZjZxSXpRCnpoN04yY0dGeGRrdHhOZFN4UmFZ
            MEkrRDcwS0lTd3BnMmdhR3ZNYzNnakkKLS0tIE9najIwRGsydHhObFd0MmJmTEdH
            dEVoRlBqVmhWN0phK0gzUDFuNWRIWlEK6SALIpsAgFVF8iXVr+dYBexx2ICi1O7c
            IJmgSkykM4ifaK4ZgkspKx0vaZZsOdPTK6Q7TdPlLAg7/wPmPEQV9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOU1BsT2ZKTTdzWHRmWXlo
            ODBHRExnN3dUaktTcDVTQnFLbkN3Mncrb1JvClEzQTlGMjlwUnY5SE5HOWJhbGVU
            alloZ1ByQlZGM2d0UnNaRmFsY283K28KLS0tIHdBZGVYcy9TY2w3WThaeWNYcHlU
            VkUxUDU1eEtnZ05XU0ZEZWVmVEdYZDgKVCPTwWgHDoZ0kxqFre0HZ5yh8vadJ0d+
            uYkEcU3mTT6ciaixLSBYeuIlf9FaEKGwFy+RT/3a3nrAJbO94WBJ0Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbk5wZEdLelZqV1BTNWxV
            ZVJ5NG5rVmR6dXhMQzV0TmJWelVNcGpGZDE0CkpVSm1aOU5XVlhYdkIxbXNXUHI1
            TDUyZEt6WVlCb0ZvbHlkS1VEaG5tYUEKLS0tIFBaNkZNa1g1YnNhcWRlQkE0WFlk
            aklKcm85NHRHeUFUT1YvMHJFaW5zY3MKKY1FsKi7IFhAaj8/AAqhd6qhlondirtp
            K8UFWT+3Y9LCd+F6MeCZ8fdPRSlLj4BfekYA/inkVh5xpGnYNTgNGA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcWtIS1MvQ09MZmlIT3Za
            cDVwYUYrODd5cXZlNXFNaEhXMDY4YTQ3TlZnCng0RHhwcDFFcUNSc0xzUEdYWi9N
            MlB4MmR5djlWRGdxK0Rzajc0RlhGZW8KLS0tIHUyK2hWTzF0WWdWNzhjZ1Z2aXgy
            a3kxOWgrWTNXaENZaWM1dFRORGdKWmsK9IQmegaj5y4WWhBs3jOL0CRNh7iE7fax
            thNZL4rS04fjPVT5AnsMYsXCediaLB7qdBM4YutAxtNJqib3tq3xcg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MlBiTmwydVAvdWVSaEk2
            Nlh2bFZvcGZkd2FhSldWTFBxcUJBRkVWZDNNClp1dytoL01tWDBrNUMxWGFHS3dx
            YUpUOThKU2VBMDdVRWVEM0JCWmxzWW8KLS0tIGp3c1FpV21xSnBubHFHdzJ5eGtk
            VHFZWGtpZTlJa0ZQV29Ka3N1eEFQNUUKXh46Cuik//5L68Auyz3MQ09KkxQmoKA/
            NBz826XrLKOfJMFODTtDCIZk54/EXlEANTDFL3aMXFgYe886Bb9XLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTUtHRzByalkrRXZQaGZK
            cklGUDFGRGh4M1loQW54akR0REZvby9HTmlnCitrSlh1WU5HZ2kzcEtydFhOVUxu
            aVNvRE9BS2RiL0NpbldHSUVRU3NDVTQKLS0tIDcvQ2Z3ZTNWejhjOVMwa2VEd3Bs
            K25ra2pyQ2xucmQ3VCtYOEZNOTJBQ3cKU/pEhb9wuinqKMIHmeaPb3/qY8GaggxL
            aW8Ft3ipzER0VGptNWvdgM45fwyVtTUfeNQr9mcNdiM5aEySsAxUjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-30T04:55:53Z"
    mac: ENC[AES256_GCM,data:w6k8ySFXMFF+j0iSmDqUOFxScjTHJt9VwFvLrbh7CPqQCUh0njlMs1zOwfefX6b6kcW2roACj7yHKL7k/78RJX9nHAMrgFYUp2pcV9NojQHytsNdWqsRpRObWEEeSEOEWxo6pJ+J8sJsht23XR+aZ03DZ/5m4xnT+igRbcXMNTs=,iv:SBz90Vu6UFpQKS64lilH/dEBierYl6zgeENcYrpA0yg=,tag:/q6U7QvluLjqTkA/sLHh1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
