prometheus_pve_exporter_config: ENC[AES256_GCM,data:CjvoyuR8xyzsRVixtglLr/np8/kMRA0AmFvo64S3qLw7FKi1i27+8EudEYxHE59qsI3Mo2x59Qw2HVnLDYNxDFpplp3zUbM=,iv:zR5umjclnyq8d8bfNmWVST84X+c2jx7zRlBwzxDDHUk=,tag:cOxtRkcwwkORqemL6sDNfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMjRtTzNnM3hCRndITzNh
            RVRPRW9GS2lzNzBsczJNWGllamloR3VDaTBZCndhQUZwS29Zdlpza3FYTVJhRmxH
            alFmaDF0akFNaFE3UmJQbzUyYnBYQUEKLS0tIHpoTWhNY0FTWk5VQ2IrZFV6NHlu
            UGp6Z3BkZnhyWFlJQUZpeksrUFkzNmcK4d0M9sTlb7OiiyMJVvO28o/Z1VYONa2b
            I0qwVDIkfnU0kpYMVd8A1M6ZZshLBVnYpm6SCxJn1N0bEMpX8Psbcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Q0Q5L200V1ZHaU02RVZQ
            dnRxUVgycU02R2ZkUVIvajhvbjlvS05tcGlzCklHYmd2VWY3bEIxQmxxTDdQNmwy
            L1Ric0poZ29idmdSdEt5dHZOaXJ1MEEKLS0tIDVNNmJpL2plZHgxd1YzemwvSVRD
            MnQzLzlTQmdBa3ovYkIwc1orZ3lIdXMKMEz2/HxR7JaGLcXgINVCQUJfj/E0Upi6
            dpO/BgxLTzKuOImH7uxNPnCxvTPh91eOXbAq0fxFvRw5OOZMaRhhvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g22ghnrdg858yv6w2ux8hgntj8gkdyjn28axdkmzyx38d4vx6geqj4px9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZTV4dnpNZk92RG9EUU45
            TGdSQnh6NmFHWitLUG5za2NTQy9LaW5LK2hJCkQ0bnBlR2lSMzJtNVdTYnNHa2k3
            UU5BZ0NRN2Rtd2QzOWJEK3ltSkpHQjQKLS0tIEExNXVCUUJ1WDhsaDJuWnc5WFRk
            aW01NTZwV2RhZE9DSG14clRrRzU1OG8KWxbqCVxpgE6meENV6HxuVl7wHDRJocrQ
            qUqNUCoqxHb6qbxyCw0whlAx4Ew0hnxBSFrrwbi1nGlFKTlfEw/8xw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMldMa0xkVzZKKzN3aGZU
            b241MEIzdVpWVEtteWxzNnNPckpvamVGUTJrCkJidjdQem9ONjRDdUxpM24zRW9s
            dGRlSmVJcDVwRXBuOERESEtYQjF0TFEKLS0tICs2U0hzdHppSTVyT3o3eUxSdkx4
            bDZSOFd5cmk2TW9JYWFFT1FKTGczem8KcaMqMRtKhY9pcWhXBZa6utmjrU+V6fQh
            z/UmG8UwzheXqnPqvPjQIP5grfao9foDYSQIH/Mdqckk7ei4UamD2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6U2lkUGkxc1NUUmhtNzNF
            VUpHajFtdGpZSEdZVzJGQ0cvS1dTMjVuZHowCkdPVXhtOE5tc09lZmdpNWUyN0Ex
            dmV5YTZOeXBPTmc0Ym5HUFd2UmJhSU0KLS0tIEl3V0dSdm1sd0FJK2dGZHdXVmlL
            cXAwTmE0Y1JaOU81WmZaS2dxWVdiYWMK5XyCLs7TNx6i3UbfZbnBfvNjFX8xuo8B
            r1WswaKMPc2cO0y6PJV/tG8zajm3gfqcgfsHJC1sns5u0kQ+oNX+lg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZWFYa0RxbXVMUG51alY0
            dExDQ2p1aUk1Z3J5d3ZmNGo5RUVZL2xBV0NVClp3dXNzcmFScVh3VkZKcEdjTE8r
            WDVJc3NxdVh0KzJHcjlucUlGSW95TDAKLS0tIEk2RzJNdW9jOFAvb205cnZPalFq
            OS9nTVU2MDIwTWpKTU1aZ000Q0dMd0EKpVn309whExK6m2L6uNKtVveM6+fVW6k4
            2kEN1uXDRiy3xwAB5A6BXkFISiR8NRcjGxLf8ceYfzVlQuvQFf8ijQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBneGMxcXJ2RXVGcUxyUXlW
            eEpVOEJaTSt0dTRBcUl4K1pWeEMzMGo5djJNCm53ZC9PcWJLZUpZOWUwQXR3Um1u
            eWgrU0ZITnpNUmJyNytKaUx3MmUvaFEKLS0tIHFIZnljK1p6Um1ldzdvS1VNd3BN
            bG0xcW1iWVdva2RVa3NYbTRHdkk2TVkKUkj2XBQhLzzpKY0MqZ+9gBMC6/bP8ica
            h+btLbV60I+GtOSeU2r9YeuMWgOuFsXaQdS3SkHKq3ppGHU6kK0ROQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdWxWQ2xEVWNuK1UzSGNv
            K2hia1ZKNStRa3pXaTRjVWQzNGNNczZFM21jCmFCWGRNQ0hSWmtzVXE2d1VaenZu
            RXlhTjFUdmwydExSQWpCWm14NGNVTzgKLS0tIFh3MHBnRmhnYkJuZUN4WDdkbENk
            VlBISG1mbm1ndytMcVZLdGliMjd4TVkKvANn+IMznvHi2qifx637X7CWP/+2pKYb
            0GbzCLnNAvxi78Jt2pNDC0CWl6yQ59qLt7FJHFg+Yp5h1n7uBahCLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x708x83pjj7urp26pncx67fqz8a3htrf0umw7c00pvmxhl6y95lszjgd6r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5alJOOSsyWlRCTUR2b3M2
            SExKb2dNWVlTYUswVVJSODRXZXQ0MDg2VWp3ClZ2MUVPbVFmWFlObkVDN0hkanJu
            eTR5VGRmRU1oK0ZOZklSRTRaSlAvL00KLS0tIHNJRHRUQ2xHbXNtdEc5R25rUElX
            aUg2M0pseElnRGxXNWxMZVVpc0EvTjQKi3MzolMDXhlb5VZXn2XrsZiFekqLbFlz
            TmC2+Ts6iUzWpTpj0YhlRTNdQF321WtsQa4qC2op/6BAPYZT1QEFCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12yvljlgg94z8qfwyezz6mtmrpldxvfcqwzsuyfekszu296fg6upseeyc0t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjY3MyN1JLdkRLd3pLM0Z2
            RTBsdTFTVXlmMWNtOXNzcXM0MmtHUTVGSXh3CmZrQ3d2VXJjME1JaUVUWWtlNnBX
            Zm9STjF6Ym4vN1BDM1lxZGIwMyswZHcKLS0tIFNDcThmNHU2cjlwRkdTaHFwODBR
            ZHlaV1hvUGltbWtWbUFwL2RNMzMzSDQK/uzc7Op+qALadYWl0+4fF96i6mkqnkCT
            pjBQL5jn+r93xO5XNT9XseDTD0hDlezhvNdPSdLk0x+WHqpKcrHOSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15fqamv69dmkds8twydjtguj7s3lunjl8t6k56783chslplex2upqzn68xr
    lastmodified: "2024-04-30T04:55:53Z"
    mac: ENC[AES256_GCM,data:w6k8ySFXMFF+j0iSmDqUOFxScjTHJt9VwFvLrbh7CPqQCUh0njlMs1zOwfefX6b6kcW2roACj7yHKL7k/78RJX9nHAMrgFYUp2pcV9NojQHytsNdWqsRpRObWEEeSEOEWxo6pJ+J8sJsht23XR+aZ03DZ/5m4xnT+igRbcXMNTs=,iv:SBz90Vu6UFpQKS64lilH/dEBierYl6zgeENcYrpA0yg=,tag:/q6U7QvluLjqTkA/sLHh1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
