prometheus_pve_exporter_config: ENC[AES256_GCM,data:CjvoyuR8xyzsRVixtglLr/np8/kMRA0AmFvo64S3qLw7FKi1i27+8EudEYxHE59qsI3Mo2x59Qw2HVnLDYNxDFpplp3zUbM=,iv:zR5umjclnyq8d8bfNmWVST84X+c2jx7zRlBwzxDDHUk=,tag:cOxtRkcwwkORqemL6sDNfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eVBJM1dscG1CVjFPa2cr
            bHkvZ1BiT0NPdHduSVp2a1dKT0pkbk5uUnhVCiswOUEwcittQnhDWk1KcGc4Sy9M
            RXVMcFdLdi9CY0g3dmh3R1pMbnlWNHcKLS0tIFhDV0RkTDhXb0ZZREY5dWpvZFJY
            Q0NKaldyUzVGamdIWjdEb2NySHpQd28KzmLW3WcGgeAEPQsYAZgZ7czMRsrt2vv9
            v0OBeNbgucrladbDuDxuPH7Ua3UiJrq34hPPzg76k4o2v3jI/8tSQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TG1BTkkvQjMwa3lPR21t
            NW5oSTVaR0FFWGduL3dPQ21kNHRrWGgvdGxFCmZRaTRsYzYrYXJUMHhoZzVFU0Ja
            YVpselI2anJ5Y3dST3hRYXRDcU9XUlEKLS0tIGQyRXg5N0hLQ29GYVZsRkFiWUVL
            VkhZbXMwV0dMQUpSV2hEZHVnVjFUNFUKLOHhNhYD3y6C09G3lAn74kLIv+b336ul
            6CMsKItYYy/FxCILNuWbJFNPEfewVqAALnjOMwIV3Ga9vwTvEGmcwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g22ghnrdg858yv6w2ux8hgntj8gkdyjn28axdkmzyx38d4vx6geqj4px9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNb040cHZmZUV3eWw4V0Vo
            M1NjZEdWcG1ROWZuc1dtWDM4QVBGR1ZwTUVBCkNac3NCZkk4UkVBRnMweDVaQ1lP
            MnE2OEZIeWZQVWptTkpBVjBqczJROVUKLS0tIE1Oclo0S1Y0Y2RWWWs0Vi9naHdi
            UzZWUUxkSVl3eU16ZEtIR2tkU1htQVEKLdFVNHLpJUA01oQu8XjeCA9xXPQ6L2Wm
            6rq1ZVLbLJIl4LLhzY/rXg06T6S1DyVCgFEh+EEMKF31garBvFvhkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKT1NyaFZVM2VwUGpIVmxt
            UTVvK2l2TjQrOVNPZjV4U2JXSy9hVVlRWHd3CkRkWnY2NXpOcW1BdGlPSHhjRW5B
            M25Rd2h6N2NGTUU2bktxd09jd3hKdnMKLS0tIHUrbFRaaHVJcTIveVFka2NjT1da
            VjVsRDhqMTVvTEdzYnR1ZzBvb2dQMDAKvfh0MxBRAwsfHcwD0PlMDLFWaxuX22ZH
            rfRKSxwl7iPi9fm/YeCQ+q6ERGa5PNsLqPyluJyfGNOHGW6ZWeA+TA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWDdTSVRHYUlaOTZwbmpa
            VXpGZTlvNWpwbzVsTHZQV2xON3VHTFBLYlc0ClhPOGFuQy9OblMxLzBaYm9aL3Nl
            U0NYL1JtNnkzcVNadWk0UldaY0JzQlkKLS0tIENLTlJaWVdwaXlBTFM2VVozWGdl
            eE1hKzU3eVZYQlhaSTJxREx0NTlhdncKZZanCszhGq6vMxUFIWmlSviYkxQsFLYt
            eZobp89TykKTW1IVkLeCyZ1js+Yb23avYMee2geE9V4/++DOoRNmiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSit0eDZsZnRHU3F2REhD
            MGxvbG96V0tEcWlrcFc0OUI2SERaaXIwbW1JCjFMNXRuRjVNd09jK216ZWJVTC9s
            aUp5SGFQdUZ2OENvaUpZQzJvV3haUTQKLS0tIHhDWmZ4dEZ2REJJQ2ZzQlFvNlNj
            dFovWjdCNkY5cTBIRDE1OXNrUXlQSlEK7e1OTTreLz/2uTVwtCwaFTd1qOx1pYpD
            JPvC/PV76ItI4qBpxrH7sndh2bK74VX6K502kEUrVx6pMfpT/X/2cQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OVZwdFdqNEdQVUoyTG80
            ZUF4SUdCUHJoL0pzdEk2SXBPbGwrMGJwVTFZCktZUG9TUDQ2Vzd6V21ncTkxKzFu
            MkRuTHNLODdxUG5wZ2g5QktsUjZ0MzgKLS0tIEh6ODZucStaaHVaVmYrQXBGR1Fk
            Wi96OGJGaURpYzhjSHQ1QlVWaXUvS00K3lhQazt54hYCy51eJqTXHBolkFdotI2i
            jjpFEaQ4fF/C9GFXDiJzqIMOG4e4zxfHBkPILUGzbIiODz39n7PWZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWXpaMTJWcSs5dTdQdnF6
            cGg4RkRiTDl5UERleDY2c2lJd3Y1SFZVRDIwCjQvVUxqNHVic0JMMTZJUFVXTFVa
            ZkRNTTVCK01qNkdUditEZFR1ckdUSFUKLS0tIHQ4K1k2Y1VjU04za3hCVlZmMkln
            aXNjaHRuUXVOaTBaQ3lIck1ya29ieFEK+SLvkkvJNVCRM6yzmaG0RwYE82+8h8Cd
            zVGv3SWTt3kFFkJP37yjRaH4HB5iHF7UOnZNX1KKKU61K0QhP/D7TA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12yvljlgg94z8qfwyezz6mtmrpldxvfcqwzsuyfekszu296fg6upseeyc0t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMTVYV29VdW9OVEJ6ZFZ3
            ZFN5aU5lNVRBb3BwNzFqTW9BZ2E1U2U5d2k4CmZsWWNOM2hhZURRMUFOSjFPcWxM
            S2FDN0pURlJxcTdNalMxUjlYL1FDY28KLS0tIDN3TEpmdWxxYlBtcVNMaXFCZmFW
            b0JhOGpmMTl6eWZWeW1hOUJiTGNXejAKv3v3ZfHVfrJZZWSTtPgLiisImbYheCaD
            yBW2VbRhfgoLD/Kw15QdCMItFfdieLM0S+XbE2L3j0GfJUPNEE9BTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10zakwy8z5448vj7ur2h7vn8wfzvt2nxwq4pk4wx6cs34mlg58yasdjhc7l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QVY3cldyTTltdzBtK3R0
            NzVkWHgrUGJuZ2IzS1c3ajRTSzEvS2kxRmpRCkNwZW02SW9wb1FtcVljMXBUdkV0
            eUVncmkxRjAzNTJhZHFqdXo3RXdiQ2sKLS0tIHFZR2ZkdHlmZ09tM3BQVm9PWjdO
            NTVpdjVEK1pDTTNCN1FlUC82S3lzbDQKkHS43BzBHI0NXtB+bBy46hDpRMQDqu4s
            h5OiYlFKs4ba9w+JxYyipbdtgDmOWKSFoUqCEZW7sWGe8zGZnKEovA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10q5gqw4gwts228ayanvalq7c93peqjdsfqcgevd7qr43u5rhnczs9u2ysj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUjJMcnBRZFZ0WHRUUE9S
            dlFHYnhQWDBwRjVUZWh3bW9yY2RHYmxGTUFvCnlUbHJRRjVuQ0MzSjBzT0EvQnlh
            Q0c2T3NRVVJTRXg0Q2lWOWRNUlBqbkkKLS0tIFIrUjR6dG44eWhGTDAvY0FsTk96
            UnZ4dXRnQUlQOWZIcFFONmdMNVI0OTAK9q8UA7m0N0N+4bUF5BgheGgCzCRQE+zb
            UEMOtTOg/yY5t+4eAb+GW8rAI2Af1Q+kstD1n8qccJasO+b5pXZyUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hxynjkmtgcu9lwejchkjfqjp484at589sznqkxk6weucp37p4p7qaj440h
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSWc5RkIvVFg5emFXZTE5
            VHpHVzhwQ3NGOFRTVmwvYjVUeDdyTjVnWnd3CmJxUUNScXpoSjhqekRmMk51SXBq
            cnFEYjVOY0p6L245SE5qakVVeFROODQKLS0tIGpCeEJtV3I5dXlMRnhyN0pRTWEx
            eUgya1RJQ20wS2M0VXVsN2FKMEl5WFEKd3vEf39X+/KARZeVhjhta6jXrIPL0jom
            jmmFcQv/ACRvXbWFj0k2J2UYoqNfALS/b6MAG3yIacqhS0HCqoLPxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dtf3ahstj5mhzcqf4d2zc54d5dds69ka32dqpmpsskyaz04dtshq9ryxat
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSUNIVkt4T1dTVmFMNXZL
            K0JwamhMOTRWbWtrNzJQbldOYklxZitnVWd3ClNSU2cwSVVQTTYxNlluTkVDUk1K
            RzlCYzFTclVBQ3daTXlJKytkRGE2ODgKLS0tIFdOMXBrUWdVajZwSlBUd0dqYVYr
            Q1l2enRTcjAyaGhrZTVGeXFsc055RmsKSmyCVYc4/a3USpq71DIC7s0Vk+moZ4Gp
            omnljYv6s2werNrMW7W/4J+7sIzHSj0GI8/wml1ngDP4K9gaS3syDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1px3aq87zcjgts5guc59fqn64zjkqzukdwce4a0ggza83n3atkcws4h5aww
    lastmodified: "2024-04-30T04:55:53Z"
    mac: ENC[AES256_GCM,data:w6k8ySFXMFF+j0iSmDqUOFxScjTHJt9VwFvLrbh7CPqQCUh0njlMs1zOwfefX6b6kcW2roACj7yHKL7k/78RJX9nHAMrgFYUp2pcV9NojQHytsNdWqsRpRObWEEeSEOEWxo6pJ+J8sJsht23XR+aZ03DZ/5m4xnT+igRbcXMNTs=,iv:SBz90Vu6UFpQKS64lilH/dEBierYl6zgeENcYrpA0yg=,tag:/q6U7QvluLjqTkA/sLHh1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
