prometheus_pve_exporter_config: ENC[AES256_GCM,data:CjvoyuR8xyzsRVixtglLr/np8/kMRA0AmFvo64S3qLw7FKi1i27+8EudEYxHE59qsI3Mo2x59Qw2HVnLDYNxDFpplp3zUbM=,iv:zR5umjclnyq8d8bfNmWVST84X+c2jx7zRlBwzxDDHUk=,tag:cOxtRkcwwkORqemL6sDNfg==,type:str]
sops:
    age:
        - recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUnBkZWRPMkUxdTF0YW1E
            dEVGVWdlalF1YThBUlBXeXRXNVBDZUNDWEFNCkNyNUhoVmlxU2Vub1VFbGo0dkdy
            OG5vempEYm1JMXdoTzFMbXZsRnlCcTgKLS0tIE5NYWJRVi9yajZiY21oNkY5U0Fh
            cFNMbCt2eEpZUnZPUTdoSTlqSW5qaU0KwSeznTPTHRnomGBQjHDZ/YhOyBdDBvtp
            boGPFIgFFqOnFfQy4uZTVIEuKs74U3MSHOFcYG96lk9JhDvnexMz1A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age134vfx7ce3z7fpzqpcm4nlwcav0apm00g95nrrgm2y0m8wa7rvy6s765gl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaWxmelphQTMydWIrYWM1
            OURieUZrSUQ2eklHT1BZZXdhTjBDVHFHQUZrCkJPWFJoOWc4WVJSanBmMXc5YjBC
            R1ZMZGhuL283amsxMnNsblpFYU9oYjQKLS0tIExleEhFaVJxa2VUdThqdzRncjVL
            VjBoU0hycWk0WUtNQ2hyTmZpank1S00KUPbHmUUVc2e/gq8pM8ceCNyCX7+Dw+lX
            Lyio8xXkliYtqy6RD/J1jBX31EonQ4ox9ijEto0SKJ+hBitiiVH9oQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZCtPVlNqZ0pOVERYNHBi
            NjJvNDVDRkZuVk9KdDQ3RlhxUnRMUmp5QkRzCmptVFl0eWhYNEgvV1YxMHFTRXJP
            SDdUYTMvUENuNWcwV1Z2dFdNejVxU1UKLS0tIDdickpDYnplYmYwU1dIcnBuWEw3
            VS84dGd0VnJCWG5rYXVEcGtvT05IRUkKYz/TjysPhUdex9V2TG1sfv9JAees7SCV
            lkwqER8Z4ZtpetW+LOIFvVeDL1paAhucuFZ7OvXbJPurGCmjqVl/QA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NHNHS3RPelNhMG1kdDZm
            TGVYQ0tFQktKZzUzRnAvRXBPQ3UwUXkwYlhrCkhuMmtuczd6a3hCSnJoYmg0TDlL
            dERrMWdjWjYzSU9SM21tTy8yV1NLWmcKLS0tIE1YNkljcmZIY3A5M0hUQ0pjcVRz
            U2RPc1JjcXdzRmNRVzhXSndia1ZVMncKPVqmUvSvu2rfm3YRp8zO5L/ISMd4XIsv
            dWUgPgdXxO0TVGszNw6VNaBnZ0PbPb2czSLilBev949gHMgxJAafHw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUVZoRWVvekZ6blpodXpi
            TDRlZmFYelVNYTdneGlLcjkxdVJkYVhva2pzCjBYdWVPZkN1YmtJWjNlQksydjlC
            QTFKTXAvMVNRRHRFM0tFUWFxSW02NmsKLS0tIC9rNnowOWI3MzlGQ1BEWnZhTVIw
            akFNaU1JODBYNHhhclZtU3JvQm4vVVEKeVtvg82ul8Wk8nsw54y8EvJcwsCeSgHm
            8myCliMoAdkMMmKRiD04QCOm6cWT7KLNTJ6A/e9n+1xl1qXyaX3W/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUzhHZUtnNGhIZjAxTHk4
            dWw0dmxDajFFZ3JjZ1lMcVVITjBxdkJ3cUVNCnNyVDdSYnNBMkZvQXRDSzhVUXhn
            THJ1T0lhckpTODZPcE56YmZKODkxakkKLS0tIDZ2V09sU3pmamFIbkkxdS9sU1Ax
            Y2JwUUZpUUY0Z1Y4Tm4wajJleHBNMjQKh8NPz1xfCiOUG2NRRVbOeg5y0fOrhl3C
            WuUUIcJizoSbytLFofVTl91+7N8UNDdi/Ffryi3sRM3mcP8YqE5w5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bWd6UTVvalRacjV3L0s5
            YjlkYndRaFZOaFBKMy9RVjBGeHFnVXBVNHdFCnJIVjROaXplNEJCMHhqTjBhek9u
            RXcwSDRSSmVPWExqZDVOVEtaQ0FvSjgKLS0tIFIwU1NBODJrVGRncWg1T21UbW42
            ajFidjRFandyUGx0aUp5OHhKTkdaRjgKhiCRUXvYX6Sz8KfX58w61Xp5/rdQ64SP
            dMiXUU21uiOxqQEo2Oi0+SCyaupJ1r0ZJ9G7s6n+8gQ5tquOUzSZwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x708x83pjj7urp26pncx67fqz8a3htrf0umw7c00pvmxhl6y95lszjgd6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMFdqcU4zTUhROGF2Sk4w
            a3pCSzZkenUxck1RYzB4Ky9JK1FHOG9BMEVZCmFyZ204MEg2M1lIK3pyd3ZPaGpG
            ZFdZbmI1R2d3U0NmV1RWcnp4blBPeTgKLS0tIHJVbUozaHpBeEt0aHRHUElpLzFh
            RGZJVmNtYmx0T08xOHEzZEZUY1p0YTAK1li6++RkJYYII9mY1mNzemfgKHqz3hmb
            efSVNJ3ZqOKard3jRGsg78OO9sEFY7HbJOiO+8Rc47lPVh59lRGShw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-30T04:55:53Z"
    mac: ENC[AES256_GCM,data:w6k8ySFXMFF+j0iSmDqUOFxScjTHJt9VwFvLrbh7CPqQCUh0njlMs1zOwfefX6b6kcW2roACj7yHKL7k/78RJX9nHAMrgFYUp2pcV9NojQHytsNdWqsRpRObWEEeSEOEWxo6pJ+J8sJsht23XR+aZ03DZ/5m4xnT+igRbcXMNTs=,iv:SBz90Vu6UFpQKS64lilH/dEBierYl6zgeENcYrpA0yg=,tag:/q6U7QvluLjqTkA/sLHh1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
