prometheus_pve_exporter_config: ENC[AES256_GCM,data:CjvoyuR8xyzsRVixtglLr/np8/kMRA0AmFvo64S3qLw7FKi1i27+8EudEYxHE59qsI3Mo2x59Qw2HVnLDYNxDFpplp3zUbM=,iv:zR5umjclnyq8d8bfNmWVST84X+c2jx7zRlBwzxDDHUk=,tag:cOxtRkcwwkORqemL6sDNfg==,type:str]
sops:
    age:
        - recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZHFPV2hyUTc2WmM2Z3Ax
            MlRRUzhXbElwMUNicDRoR3p3VWNpamViYlFzCk5ReGpJbTJNelo5NE9aaW5hcWxp
            a2p2R3FTKysrOHFXVUxhencvNXhqWDgKLS0tIG1ZUTJ3cktJb1M4SXhGa0tVSU9U
            cWYxVy9tL1RjYVZ6TWpwY3hpdGRVbVUK+4abZ2MrD4JZVJBFzaGnthV1U7weV0yJ
            MN2+VwO8SsUtYJicPl0vgSjyuWG1bAoojkZdatPL7Ef9IC3/0pA7+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxs9kx4nezjunv8a7m9cz07vd5843dxx239elz2wt0ms6u5ls97q9ud6k7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQi8xMURSVE11UmhXOGY3
            UC9TdmRUenhybEZOaUFOYzBGNzdFK3d4cUQ0CjMveTZDQmt3U1B1OTEwazl5aGd1
            d1ZGbzdJZVNyWG1aUzNKOTV0TlZjQ2MKLS0tIHMySHdMWndVR1c0bG94dW9FTlRu
            c24vQXVYU2pVdU9DNDM5Ykh6S3JTQnMKS8PRq2xvX3H4abpk/ro5ChbXMF7mrPM+
            xl1oui/BG6tfNufJ0WS1FP/qiK2gGpq6Ajb2f4eCbL7oJW5DlPvCYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age134vfx7ce3z7fpzqpcm4nlwcav0apm00g95nrrgm2y0m8wa7rvy6s765gl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUzJxRnBmeHZldVVSL0V1
            VjFLZ1VlaVJlV0hnK1ZwSjBNMWRhampYTFVRCklKL210cU01Qy9oVzQ5elFPZXcr
            eXdqYTFQbEl0d2F6d1BudkhsTVJlOGcKLS0tIFZraHEwM0NyRDJ3UHJ4RmJwdmxu
            YlRaR0pXQjMvekhmRE5QekhjRDFTZHcKNR5orjbWxf+1OQ2MD69+QduEtZcdvbIp
            cxA2AsuLleTN7RIwRP0h8MLVeS62JXiNjxRMXFGafYBvbsROvWSRNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL2F4aVR3Qyt6a25xd0lJ
            S0xJSlduK2V4Z3FndmY5SW8yS20rMFdoRUEwCnNSVXBraWdhanFTZHpoRGJvckFG
            MDF6QW1mdS9OcnI5bkJ6M1JaQ1FQQm8KLS0tIFJwK0JQaTZlSUZCUkJnYXVqRGl0
            VE9yVHBkdlVpc2lBdHhJM0JSK3F2djQKwkKHjrk2vV+BkBpNGfmKMRWHCPQNpZHE
            vrqAOAiTsoEpruKlnyFQxr7/7SrNS7/84FcKSyGaMC5azA2LfWsnCw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYkF6cTZFMVVKN1U1Nitr
            QmJRS2kwK1FiNDZoZGN3eUYvbEc0SEdXWndnCkE5QzkzMUZnWUt0N2tzZ0Ezb3Az
            U0o4cENTQWdXdWpMVDZzSG1XcEJoV3cKLS0tIHIxRkwxVDBvZmV0S1Z0WjVsdUZh
            Y0JrZ05RdkdERlh6cEJWTC95K3o3NUEKdfj8LYtrjefjra6oo3PX5Pw7PtKBFpDF
            /yW1rC03vbGfrZZ8WMSCJYSGwN4Q8qx0xjPyRxNq3A5F2sxyDP5SyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQjRoZW9mWTcrb0xXTlJl
            aEdXT1krWitwNHdvZ3JFWnZYWHRwVWJxQWhvClNHVXE3OEp3L29aVEZhM1JkNzhC
            MHAwQTlGZitrVEtFMUwzZnFMdE9ocTQKLS0tIG1RNVNrRlpaTzROR0Rkc2ZOUnpq
            S1BrV2ltcGs1QkgyMUgyMHlqdU5NQWMKIoPJbEZUlkaJ1nYgwtjhkuw/EoBwU6Ye
            lDq/AcfT8/IexikSOlAEMkOnO3JGfniEnRcm6H4g2ABpGkxmkoNE9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOT3JzSWFkbmpPd2hZaW50
            clFKb25GMmQrRlVKcWM1WEZucVdTb1dmSTE4ClJSQ1FvN1dnRkdLSHEvRFBwRmFa
            YmIwOC9jNDhMc3ovTGVYZmhVelBzSHMKLS0tIER6TkxnUU5CRTRRRWVVL2t3Uzds
            QmVhN01VSVdCOUV3aG5YdDJkbSs4N1UKWdMcYjRfPqqqMK5O2/Aptk0qKD74pTa3
            KZysW7lRcWQM8yO1vhBtgGstxRyBr+80WHFo2qgTTPVgDagXP4P2iA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbTZyTlRVZWhsRmM0Umpo
            S216VWRWRVJlRjc0SnJDRnlzNzFNSDJ1b0NNCm56bzNnNWx0QTN3TDZ0NFluUEJW
            Z05IdWJVZCtLTmd1YWMyelZLUG5EeWMKLS0tIGorLzRKUGJCLzM5VHcrckRSTzZ3
            UjZ2M2lZM1R0MWRHYk1sb0dvWkk5ZlUK8wZT0t19SqikzODo4IbV2wf9wOGP4a8t
            sFYUu6OvCOcFfwYrS5MXDcbKUTMdsTvkOOim/yLFEB4E82F9BSl+lA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x708x83pjj7urp26pncx67fqz8a3htrf0umw7c00pvmxhl6y95lszjgd6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTkpDRHBsVzRQVm1wLzh6
            aW40WjNBRmZXdWFaV3BJQXNOSU1PSjdHWXdFCkppM085S1F6alF6UGNYbVhESjdp
            cVpRV2ZtSmc5WTB0STRyZitKbjlkMFkKLS0tIHNRcnhsUGwwaHJ1TVY5UHdhUmQz
            d2lTdi9PTnFTYVVpQ1lyeHdGSHRTbjgKZlsy3MrT7iPsxPQ4pPcqp/CM6vPd3gw7
            70L8dd4vW6h5h+csuMS91fuc3QSR/94wBa4+fdYY2/cHOzaa8qJSlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-30T04:55:53Z"
    mac: ENC[AES256_GCM,data:w6k8ySFXMFF+j0iSmDqUOFxScjTHJt9VwFvLrbh7CPqQCUh0njlMs1zOwfefX6b6kcW2roACj7yHKL7k/78RJX9nHAMrgFYUp2pcV9NojQHytsNdWqsRpRObWEEeSEOEWxo6pJ+J8sJsht23XR+aZ03DZ/5m4xnT+igRbcXMNTs=,iv:SBz90Vu6UFpQKS64lilH/dEBierYl6zgeENcYrpA0yg=,tag:/q6U7QvluLjqTkA/sLHh1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
