prometheus_pve_exporter_config: ENC[AES256_GCM,data:CjvoyuR8xyzsRVixtglLr/np8/kMRA0AmFvo64S3qLw7FKi1i27+8EudEYxHE59qsI3Mo2x59Qw2HVnLDYNxDFpplp3zUbM=,iv:zR5umjclnyq8d8bfNmWVST84X+c2jx7zRlBwzxDDHUk=,tag:cOxtRkcwwkORqemL6sDNfg==,type:str]
sops:
    age:
        - recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtb3BYd1I1MG9zQ1phN3Mz
            V1JYYVJPV2hPemRkckg2K0JXSU9Tb2g1dUdNCmUvWW5UZUZaNWhTZVhWcWdBb0xi
            MUlQT1h4c3lMbzhBMHJlSUZ4MnEzcTgKLS0tIGRyTmNQWDljejc4OEJkbncxWlZS
            OXFTMkFOeVBRMy8yNGlqQmlPKzhvN0kK2ebEFVe1FIk22wU4aAHSLYT7WJyLgEV6
            wY8OIP/IT4KehU2MosbfsmkeamU8K1yj4PlGADTRkUTs40Mjx301bg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g22ghnrdg858yv6w2ux8hgntj8gkdyjn28axdkmzyx38d4vx6geqj4px9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYkQwdmZjcDV4T0tpcWpp
            RW9KUkVicmY0SlFsZDNsZUlvbnMvb2NTdDE0Cit4TEFUOSsyMEhwb2ttNy90WGxC
            MlpuYXNSWGh2K0I0K0dKSjUwTUc2djAKLS0tIE1tSHdIa0x1bTNjWUY4MXByeDJI
            ckFuYTl3bmtwZVd0ZlpQUERqbUZHb3cKfgRyh2QwsKHwhRFQ0Wm25z/BAxBvWU/+
            rpRi6RZACQMkH9d2/BcnCWsRRd2XoE7+mBzt/UgyPGXSgR3mUbh3MQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMUV6bDkwdUJaWHhiR3J0
            K3BUYUhudHZIbDJXdXlXQURycWxvZWl5K1hZCkIraE9tUHBjVHFIa3ZEa3cyM1Uw
            RFVWVFJzVmZuTU1tRWorVmovNUQ4UUkKLS0tIDE0MithcXM4Q2FZU3pkOWVKTlNI
            V1pTZ3lRZEk4MllUZzhBVnZDWEdHS3MKX2ybg/uS4E+2qPhdHbWl5dds/1QZZILQ
            RxJi1KABFByyT7y7rX4jt4LS87ykISK9c8TMixrgdqc9M7i/HlRwrw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTnp2eUdaYWlEcDFNamhu
            ZU1XV2NRdW92T0hzOHRLdmhEdGtpYmlkbXk4Cmx5TkV4OVdQQklpcXlWVlJydzZN
            ckR3Rkd1Q2Erd25sTUhRN2ZqTlRNMEkKLS0tIFNUckVkWlpmWnpHamM3TlB3cE5U
            ZWhoWE5xdXE3MWxGeldud3dDT0NFdHMKMMBVp+0BbGxs9RrYHPMOHlbF31yPdyYM
            5Ce6f1m4a6eAm1eBUFrVUbew/oSouHpGcq94rumHyRIt/uNDli8Q9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaG4vZXU3UkZVa1ROTEpW
            TFc0a0dMV0xTRWlqUU12Wm1ObjNCN3V1clRFCndQNTdtV1hJYjF6b24vMHFGMUpP
            ZTEwUkcweGxMOGNHM29CeVFNNGFudXcKLS0tIFFTdGhLREJ6WWVwZFhiV0IrN3J3
            aSs5Uk90Tm1xVTgwcEtLK3c4aUQzVUkKZ5kxkYSaYllooVIXJ5VVjCiaeMycpJb8
            7pHk1+S1kFtjr/rAUcEzSZI3ewUIRdotyxhT/dw6Q0cP1vEsESO0ZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcm4yL0lycERwRXF4M0Rp
            cW53ZU16a2F1bHpGSk1ldE9reE5ZSzdXaW4wCjYwR2U2WHZweHJHUSs3N0hjbzBK
            YzNXcmtsZ1hoaHNsS1l5RlNrSDVma3MKLS0tIENZRFBJQ1N6WGRxTVhuSEZKcm55
            em9jRHdqaDZ0bTAwY3NZMTNqb1JZeE0KJgxG41MEo5bAoYGE15l/ih6a0IGWl1bB
            BNE7HNzSOdWSTJ39lEhfMRuGUC9r70I4+d9uB5o3MAYJYUG3DYNfzA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSmQ1dVFtMUdieU9xaGsy
            SVpkODJBTXU3TWFzSENQSTBIYUkxMzc3MlhBCm1pVXZNUEpRWDFROG5SUDJ4YWhV
            d1pNeXp3VDJOd1FmeU1jR3BtOTliQTQKLS0tIEVVOEpDcy9xMjZ6cTRQOFVVNTlD
            MXg1ODRxMUpEY0NBc2JQTXpJQ0psZjgKR3plGhq0Aoeb5liMgqyGaDKy23ATbMWy
            Qbn7Djb/8Rc1tsx4LljMPeYDlFarzqBwmljLGgAVF0Z/qKPRV3/g2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x708x83pjj7urp26pncx67fqz8a3htrf0umw7c00pvmxhl6y95lszjgd6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQU1SZXpudkxuYmRvQ3FQ
            WklGemxLcUpEZS9NdUpVNGZ3VktPVUUvenpzCnVtUkk4TVBiTEE5dFkvT1JpTVpp
            cWtsR2R1aGdYSFFnMU5yYS9LRC9LSkkKLS0tIE5qc2xWUklXOHVqdGNnckVFOFV6
            K05yODhJVjFuWmtZREgxNExGdWQ3OTgKzmurxBmQuFDWFp6SSe9gmgOqNHODLfy1
            b8xxEk/5iQTPEGsjJdvwbLE5tTHny04tpWeVeza3ykaGQZi7ox+wqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-30T04:55:53Z"
    mac: ENC[AES256_GCM,data:w6k8ySFXMFF+j0iSmDqUOFxScjTHJt9VwFvLrbh7CPqQCUh0njlMs1zOwfefX6b6kcW2roACj7yHKL7k/78RJX9nHAMrgFYUp2pcV9NojQHytsNdWqsRpRObWEEeSEOEWxo6pJ+J8sJsht23XR+aZ03DZ/5m4xnT+igRbcXMNTs=,iv:SBz90Vu6UFpQKS64lilH/dEBierYl6zgeENcYrpA0yg=,tag:/q6U7QvluLjqTkA/sLHh1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
