prometheus_pve_exporter_config: ENC[AES256_GCM,data:CjvoyuR8xyzsRVixtglLr/np8/kMRA0AmFvo64S3qLw7FKi1i27+8EudEYxHE59qsI3Mo2x59Qw2HVnLDYNxDFpplp3zUbM=,iv:zR5umjclnyq8d8bfNmWVST84X+c2jx7zRlBwzxDDHUk=,tag:cOxtRkcwwkORqemL6sDNfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QnRhRTVTeFVTSGtiNXZv
            WGYrdjZaOWRUYlNCdlhZWVpFeHJrc3hNa1hZCmdYTnpqUzIxdC9yR2VGR0FqeGhs
            VGgvd3o5b0tWdllGTktVWGhtTGR1TXMKLS0tIExvTkpwODBwdzB1eTJxSWJHbTNx
            OWNKaDZTQjZ6UTVLblhhSHVCd0pXV2sK5GQaZYIccpKaUq1VERBrSbq33JAg8j6+
            fd44ETUIVINUMpDOBgnxaZpH+HphON5JVJhJGcmdNSQ3sX+x4OUzCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTGJLSktVNnFJU2J0L25K
            SHNVUm5sWkhOM25KVUlkVDBPSDVLV3Q2d0NZCm53Ui9GdlVhYS9KWm9Xay9NZVpC
            VTAwSnBjS1Z3bTE4RWdEUERXb24wRUkKLS0tIFJndGMzbk90VVRoRmJXYkN5RU9l
            S2drRzJJNCtBSHhNb0xYcjRGQUF4d2sKviP+bOeMJAt4zI6cctZcARssw5TU2LEC
            tkIe9/+Pwt+lEmgashqKx3pVoKNWns4u+SQKOE3tZSp+zWYogLd37w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g22ghnrdg858yv6w2ux8hgntj8gkdyjn28axdkmzyx38d4vx6geqj4px9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTzlzVExzZXFtMU9nNmNH
            aUREVS9GWWFEN3ZpWExUR2RyVUlyUGNkWGhrClE1V0dVZis0Y3Axc1lhRlN0ckhX
            b0g5VVlvdmRCNTh0WENpcUxGREkvN3MKLS0tIFZhNUJ4RjBhS241SzZrVnpEOVJD
            SStXa0xTbksxUmg2NlZUR3Q1bkpKdG8KDuF1fmeGhNz2uFR/ZvMPTF5z3AIMo1Ww
            7A3yo3/vTUg9uZdLQ/8Lsm7kRba0vyHBNJw+E7CCmkurCqA8wqQAsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTG1BNThGc2xvWnpBbzdW
            ZVBsaWxhdHRmSzlTN3R3TERpZFRRTjhYTDFjClRqVElWUTJ6MFpOU2loNGdoeTlo
            bVhJbGZ4Q25SbkFQemlrMTh5eVZIcEkKLS0tIDIySE5laW9RdTBKRnZ1TTdBNFFF
            TEJUU1B1ZnhMT1pDS293SHZNZ0JEZk0KHwUTfr1MgDpnvrKqVpstuxso/Rr6ALRC
            zt6uNS8AoZwxA7w+oICrie4vsEyLdgxLgCe/Q6xsnmvbLJthhYKzwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWTlSYzBxY1FjWTZ5NjQw
            REhtbGF1Z2VHQWUvMy9tdGVlek5NbzFaUkhnCnhvVEkvNSs2YnBTQ09XNU94SUdj
            K0xDbVZBTitkaElVa1JOWUFWQVJrZ1UKLS0tIE05YXJzTElWYm8yMWFYUWZJVFlm
            bUMxbU45b01VY0NzTDNBU3RxUHRseW8KhY8z83tnGEAxmgd+loEmNsRbgjm2xm8Q
            r7UsVwPGX8GsnWU/j+8HOj0AfSMywQAoYfkATP6r1+R2IH7EFxzS6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFV0I5UkxNeUxabHJkQ1kw
            dG1mbml1QmxkZlI0YlVuNkt5dENGaXhnQjF3ClQ3RTV3SjBIa3Z0eitkWWZ4Q2VX
            NlpPRzcxRm5IM1Y1MU42ejFvVnR1MEUKLS0tIHBha2VCS3EwODBxZnBWc0xGWFF2
            Q0JnNVMreFl6UlE1WklLQjREV3pXVk0KcsdfsHJ0mPmLKMfnjpJf4+ldG77hFlBK
            CzVbeM7iOQmCPs1jeRXrEjhnYDF4DrpEydbG1NhCSdbTfOlZz9jgSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSVFqaFR6eTF0a0J3TGNN
            RmQrNGVBZFltWjB1VnVieUluTmM0K2tnUFZjCjZ2R2NUblkwd1didlRkRkxnNHJ1
            ck9nRnJEdlB4SzU2Z2tvcnNEUXRrSVEKLS0tIHBzSnJXWTZlWC9xdlAyZmxNQUtv
            REZPZk1Dc3NKZjhKN25lY0NHd1Z3SjgKol9Q2Z3lWOL8h4evUbpMyjA6RCA89QLd
            PIJZNh0PctncJxJox2cPv6nQMRbFxY3x+g0HqMuwsXzfqQ+DNWQzGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcm52S1RZMVhWdWQ4Z0FS
            Y1BSM3dRVlpWdGdHaDNZeFRlNGFXZVlKaUdZCjg2VCtVME5tQjNRN0krblFIaUlO
            TUlIUWNSQ3JlTm8rTDJNRnYyQk5VeEkKLS0tIHZwcC80ZWpCTE45dEtJZkx3enJl
            WDJHZ1ByYlhJbE9Xdm15eFRZaEhBMzQKPgwstEPgoNzPf5yhA7Y6bARplke4q3Z1
            Qu9P5CMnI/w5/Bl4ez1RRM2VEh1cLs//SsjM97fT5IYF3X5CPJtAmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x708x83pjj7urp26pncx67fqz8a3htrf0umw7c00pvmxhl6y95lszjgd6r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eFc1cVRScEhOTkh6THlR
            Um9vMHF6WnlRVm1LYVhwdGpyWmhydERDV3lvCnZlM0VnVHJ0b2sxNjlkcWtvZGR6
            c2lxT0g4a2RZeGE1TXVMamJQUVBZUVUKLS0tIDBCcEgxZUhPcmdRR1dXZWRSVk1Q
            N3kxT0puTW90UlFkSVU0MVpQOHJ1VEUKL7/OkUBczJ2unQlArvZ11KQLfiQaZLLy
            c4nwe+bIKdwG8MJBPLRe1YCuWgAt0qY1ylLSsmeNNeXIfrIYnczYOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12yvljlgg94z8qfwyezz6mtmrpldxvfcqwzsuyfekszu296fg6upseeyc0t
    lastmodified: "2024-04-30T04:55:53Z"
    mac: ENC[AES256_GCM,data:w6k8ySFXMFF+j0iSmDqUOFxScjTHJt9VwFvLrbh7CPqQCUh0njlMs1zOwfefX6b6kcW2roACj7yHKL7k/78RJX9nHAMrgFYUp2pcV9NojQHytsNdWqsRpRObWEEeSEOEWxo6pJ+J8sJsht23XR+aZ03DZ/5m4xnT+igRbcXMNTs=,iv:SBz90Vu6UFpQKS64lilH/dEBierYl6zgeENcYrpA0yg=,tag:/q6U7QvluLjqTkA/sLHh1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
