---
- name: Configure OPNSense
  hosts: opnsense
  connection: local
  gather_facts: no
  module_defaults:
    group/oxlorg.opnsense.all: "{{ opnsense_collection_defaults }}"
    oxlorg.opnsense.rule:
      match_fields: ["description"]
    oxlorg.opnsense.rule_multi:
      match_fields: ["description"]
    oxlorg.opnsense.nat_source:
      match_fields: ["description"]
  roles:
    - secrets
    - opnsense
