---
collections:
  - name: community.sops

    # NOTE: Using latest while waiting for bugfix to be released
    # https://github.com/O-X-L/ansible-opnsense/pull/430
  - name: https://github.com/O-X-L/ansible-opnsense.git
    type: git
    version: latest

  - name: community.proxmox
    version: 2.0.0
