sabnzbd_api_key: ENC[AES256_GCM,data:q8y4tjtjcYE84xXzpZNcIrKtnqlHk7USAiTca60ZDNQ=,iv:4yUrvqGTKj6gs0eNJDw+yHkrDt7lilTVUS4FEHtnB1A=,tag:RuWEVgHiywLQ+Hu0OZJ88g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR2lTQ0huOFlDRUJhT05L
            Uk50K2hTVzErc2x6d1hvY1BsNURLOXp4ZTI0Cmd5MkI0V2JIalZNaDIyY1NEdnQr
            VEF5MmN1UVJTSkdPQktnRGFDQUVwaXMKLS0tIC8xSEJaRUVnaHA3aFFPUnNpenE0
            OFFsNmVOcDh0MjdEOXNsYUtyQk4xN00KyNSEmz3VBrw/x6Naifwybw/3p6mAdw23
            D7CcZcvRDvw7XLNMNWbhGCqvI26mJUa5zhvuEiqSZyu/kmM005hTnQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17lsd78hka8rmuvmmx6d03cqjl2h55lsvrnzdfq0ge4acujf6nffswdwvr0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNWkvd0xKN2FWSFVZcisx
            VDFEeFhIdjZwMEFWUkNUTXFIK0x1U0VwcEg0CnVyYXBrNUNVaWlveElYN0JNaXgx
            VkdBMHdqRURhbmU2Sng3VTEyNzE5bGMKLS0tIDVIQ0pTRERrUWo2NXpuajg0NW44
            cHBaajZieWtuZ096SFZKNVZMYjR2UzQKCRZ99SH4g5tiyNK9WUaXoMwiShM414fR
            fJISSR/NJvSdF/YdsSNB90Qi6F7ndeWxf9fpaHl4uvAgAPxXp3ov3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jmr8lvn5wmxv6w0lk3vapawljnqfvws095ale94mthcgxueza9sscqq3h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTTFMd0JIUWVGQTN0VmVt
            YVJIbFJOTXUwL2ZsYkY5THIyWnJTdERybmdNCjdJTzExSXBDQ0dEcUo0NlFUL2F3
            MkI0ZlBrN0dlckRSZ21EOVQvVTVNRjQKLS0tIEs4MjBuaFhiaEtBQmlIZkVnTmNL
            MSt1aUVMUjVFL0YyblBKbWIrZjVJV1kKPDcA6SWIM7FjrzxNz/klIg79C2/hLuPP
            eVop81RbEMv2FdJUqhfcqYW1L7ChzdsNLaiJezDTdnjGP7J3sCRdlg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cElWSW9ObG5UMTFYakFk
            OEZmQ0RrQkE1REVXZElvY0huUTdUQTdXOUZVCmRMVjFFcHJLamRlQUFUQjdZckFr
            NjR5T2NNUVNZZkVxYTNMQ0JpVit6OEkKLS0tIE5rak50SXJYNkhrNE9NcUt0OTBV
            OXM5ZUxPdzFhOUFmOWozdmFoaWdROGMKCmU9fyVbBUhzlrksE3i5afJ88CYoYvCn
            5FYAVBIUwfUxa1xiuRxr4riV0FvFDLefY63BwCp9Ifk/eMEsliCsPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzekNzVy90dmQvNU10VUpz
            WXRZci9YZGpPMm1EMExGU1I4QklGNVNIU3lrCi9EWXlHY3pKVExxTzg1L2xmdSs1
            NW42V2xhSjZObzk0Z21JZFVzaG40ZFEKLS0tIG11ZUtneTdTRUZSMmRGWTc2Um9i
            NGd6L1g3V1RUSmF6ZEdnNU8zUkIyR1EKkxlMtr0bzjM8mheHQXF0rGpWXrroUutA
            iwV82kEvuZjn5ooqQbZtfa4qRvYsicRkNH5NQ151hJLrVqS3b7g58Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQW5rUGxBb3JuWnB4VnpE
            bnJUUUNvV0MrUGdrSDBUSFBvdGtpa1k0NEY4Cjg3b0ROV0psSzVvWnVkUTZteTE4
            TVdvQlJ6YmZKdEptMlJiN3lVd1ZmeVUKLS0tIEVaQStJQ3dkMHArQTBnMmdFU2lh
            L1djQm11eWNEY0t0MGRTU1hPY0swQXcKuNG6BvvuwLbpjmzMIwjLbny0bytF/Euu
            X0tF5ScpZlKjPQaqMDxp9ZuYsNPyPu4wyIWctNY7AT6JZpjmcq4LZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdzNwc01DUzhvSmU3NFhh
            Ly9YQk0raVA0YnVFRTcvUkpocitTOXVDdFhnCmJpNVZ0V0N6MFRZRHRSSGdWNHB2
            QXZSK3BaUGRjWkxqeC8rMThybmV1VjAKLS0tIG9ERlFmT0VBeTZXMnhUQmFrMHZ0
            LzhiZzh3czJKcGhtZTc4SThWa0lMRDQK/nEgUeZl9IwzIVvIPWtzML7OlzD0VaHW
            UzKM6oahS8rB4WFdZ9icBIdRKvMJXVpcES8ZDyrL8unS/DWh4tT+ng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMWVvVVNuNStwbU16eWtq
            Q1Z1ejU3MDMwWFluR1YxQVNzWEg1WEFwbFdNCk1uVFJWS0UyUUxJZ0pVZGtUdlY3
            Y3QvcmlJcUsybjQ1YmxHWTFDcHpjNVkKLS0tIFczRC94dUszQU05VVdpS2FIdDJk
            MGJPMk1zMExXaEwzUkQzTWVLWmRlOEUKYyfolQ2Y0NSiKzSyqUUdLVaXWFQhsENy
            QM+P98FYRDb0nK2GNagyZj9BApQscxcjhaeICtDNo4XDxC2tQ0cUiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-26T18:22:43Z"
    mac: ENC[AES256_GCM,data:c/sqp1xQeTsAfEsQIND4++LB9V7/wKLfYDop84BEArn/igFHejlStH57AD7/hLyxevQbbdKEj0mM5RE4KiKiGI5nqxRBV58t/1nF9OCS88Y8gdDP+0A2mVggDCv4wEeyEgueMIz56cHo6rP0RqSC/pP84vJtDsnVCL26HKy1CpQ=,iv:4Uym4cXRpDG6f0PYrac7ylam6b2gqW/JhH1Kb/c3IaM=,tag:im5rl9BB1NjNV/mi5Qr+bA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
