---
- name: Ensure jq is available
  ansible.builtin.package:
    name: jq
    state: present

- name: Add Tailscale repository key
  when: ansible_distribution == 'Debian'
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.noarmor.gpg
    keyring: /usr/share/keyrings/tailscale-archive-keyring.gpg
    state: absent
    validate_certs: true

- name: Add Tailscale repository
  when: ansible_distribution == 'Debian'
  ansible.builtin.apt_repository:
    repo:
      deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }} {{ ansible_distribution_release
      | lower }} main
    state: absent
    update_cache: true
    validate_certs: true
    filename: tailscale

- name: Install Tailscale
  ansible.builtin.package:
    name: "{{ tailscale_package }}"
    state: present

- name: Ensure Tailscale is running (on Arch)
  when: ansible_distribution == 'Archlinux'
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true

- name: Check Tailscale status
  ansible.builtin.shell: tailscale status -json | jq .'Self.Online'
  register: tailscale_status
  ignore_errors: true
  changed_when:
    - '"false" in tailscale_status.stdout'

- name: Start Tailscale
  ansible.builtin.command: tailscale up --authkey={{ lookup('env', 'TAILSCALE_KEY') }}
  when: tailscale_status.stdout == "false"
