---
- name: Install mosh
  ansible.builtin.package:
    name: mosh
    state: present

- name: Install fish
  ansible.builtin.package:
    name: fish
    state: present

- name: Set fish as shell for root
  ansible.builtin.user:
    name: root
    shell: /bin/fish

- name: Install htop
  ansible.builtin.package:
    name: htop
    state: present

- name: Install iperf3
  ansible.builtin.package:
    name: iperf3
    state: present

- name: Ensure iperf3 service is running
  ansible.builtin.systemd:
    name: iperf3
    enabled: true
