prowlarr_api_key: ENC[AES256_GCM,data:IsVRBCBfyV0TtMO8h5JIsgtTPcEwOaL6zPMF7tPYSyk=,iv:XZ3TtrcFkh0jI46gs8EbU2AhpXIiy9y1Tq//+MaxePg=,tag:8QxUyf4lJJEi1PkXE9Axjw==,type:str]
sops:
    age:
        - recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSjk2MmFkcktzbW1JNW1Z
            SnZ1MWpUU0FMTU9jektjbTdLOTFlMmxLbzFBCk84R0cvcWgrWlVLVkxLQTVPcCtV
            T3BtQ3Y3bHlabHg0MlVMRzd4R0h5NEEKLS0tIGtCOHJyZ21GV2lOb1IyRWZ4MEMr
            TEtUQ3FiYUQvdG01a0RwZWRJQlU3amsKmC2q8WucIIg/CGmO9KjlPcPukUnBp9pz
            vLldPqsLw9sy6jEIGnCutSJeBK7h0mVkwl7s+hSiKXZFZ+4+ew0CQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age134vfx7ce3z7fpzqpcm4nlwcav0apm00g95nrrgm2y0m8wa7rvy6s765gl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUDlwQkZSVHdUUWRWcEFk
            dENkak9LYlZWZkV1dlRIRXlzMnNuZVRjSGxnCkhqMENJMTBiVmdJWi9KQlA5SkFP
            cktWTTNwOGhHQzhoVGVlb2lydDB3eDAKLS0tIHBnUWZxREVERW5HY0wxMTYvb0hG
            ZU1ReTZtSVlHZVI2ZnhleDlydlRPKzgKfAnuR6622lyeNwJYsNfIRj/66zMmRzTA
            ITjol+BBcJm2DSnCCKoAuzY3Nouv0q/h9BmpVWu55HklCvmI6TrZAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSmRVSzlPOE1Lc2VRd3Y5
            WFBIOTljOG9BTU9xaDhNVWRSd2Irbncwa3hnCm1ybzRXQTdSa2JrQ1p0VStHOEt5
            cXUrN0x5cFcrM2ZpcnVKUDZPV25hSXcKLS0tIHFITkRVRjVtbGY0MW15RWE2aURU
            R0VSMG5Mblk3Wk1LN2VYeklzb2ZPT3cKQd6KG70IP/B9MRwPrutgmRByryS6cn/q
            3NRXnwd3H6Fh/ruz93LqTQTsq9AW3JmMNwgEtBkrU0YEuvRJAhK6dg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NDJpVEdBYWUvdEMvRGZ5
            U1Z4L2RaeHNBS28rZzg3ZGpLM01taUlGSWdjCnZDbVV6M0plRlhydVZBbmtxTllT
            dGRQRjY4UGI0SkE0eFpLRU03cVZSUFEKLS0tIHRUNXNwQk1kdno3K1BsMXF4K2Uy
            enpTOVlLRGdRRGpleW5ibEVYSldQcDgKSGVGiVorAPrhVd7xQZoK25IcQ/Ety9ah
            VRV+s+2xrq7W5LOEH13eZ+lxwPTB5PzuPeb40uiHESc/WhUgjmH8JA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVjNqd21objdXWnJ4aG5T
            UGR2YnMwYUJReEZVQ3YrajM4cmFDY29kdWdFCnVwblNXMU1vdXRCTjNnQ0ZPc1Qz
            eEJjUGlTNDN5VmFhVVQvMU5PK2JzejgKLS0tIEF1TzRkSjQ4WVY5VnRzMkYxdWJm
            RjRscWdZWElmelZ0bmoyd1VMbDJlMk0KRyrRKeVbYTch1tiUhj8UqRtIP3ZPEArv
            eTfHkVv7Er9FOBOy+ABqm1N9+GCQFHbuJO0egyM/RMciK8LeqIrVNg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN2w5S1F2RXB3Z3FPd09t
            Qmd1cGxCcCtrclEySGJ4MzlJRXlObUhpUWpjCkp5TjlTZHNFWWE4aWI5MUszSnpo
            TDZOZFVwMUs5dWlCV21lMDlMTTFPUGsKLS0tIHR2WWhudnhOTGIzM1NXY0NHcWhr
            ckJIWEhoRURqUzVUNm1vc3FsM2ZxVmsKXqJNSrre97coESPL6RsEDrsbhnlYtpB0
            l8DSGdZdDyWKTqpHpOhEOTt1wCd1NLDi58R2vpfmiZk3/B/nLVljmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoK1VNSDgzR01ZRnVISStH
            Q2UweEV3aFY1MFBFdXN6aEoyUDlnZ0EvaWkwCnBnSE1WS0c3Y0FnbHdlejJlbjdV
            SVIxL1BXTEZrQUhqcmZxQnZXWGlJOGMKLS0tIGVJaGc0bjJmRmhac3BrdWZkWWFt
            eHZEaWFzS3c2N2RLcUUxUExPSW1BQVUK+idRKc/Kmgj2jIe/9yDtuDdWnVXwxhBC
            HuxUuAf+DVo6eEe/N8E/V5ebbeLajbOvaGysu7+HLESQUvm3/dsRww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x708x83pjj7urp26pncx67fqz8a3htrf0umw7c00pvmxhl6y95lszjgd6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkODdsTFE1bnFOcWpNb2hh
            anR4bXVHWWxjTTduNkdzdk5kbnVhekpHVm5BCm56N1RDWnRnV09hdUdUMUF1OGU0
            SThWTlZ5QUUvdmhOdU5KU2JyWEorMzgKLS0tIHpsUXpaZkdlY1dNYW0yaDFOcG90
            ZGVtNmt6Q2dHS1RVOVV2WWo2Ky9ldmcK7bdMS7x7kHdh2zCfqOuEYB02LzTFvemb
            cSM5hfdd5W6EOmfXtK0MqAdxKCO62NR++TMM9srpy22dnsSoZgYz7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-26T04:17:38Z"
    mac: ENC[AES256_GCM,data:f9VoqBa5HZdSYSbBgbyDfo+M+YgQUQu1J2tTD/1Uz6cVEfhs534wvAgg6Q6B9uAzcjPJAZSgdC5PRDSSuq02FNtOZ+CWd9cNtQlKXNxF2annIV09Lz9K8b1rU6nCs+3x56csvaY7VtL/M4StOnRlxqmL0MTgqRTSbOaQQcNI7pw=,iv:w+Tq1/PdcUQnb4K/1M3S6jQjAASmLe8DxqJ8W1XfIC8=,tag:W+KE8aAxyEsvnjxDfI4X7g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
