{
 "title": "NVIDIA DCGM Exporter Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(DCGM_FI_DEV_GPU_TEMP, instance)"
   },
   { "name": "gpuModel", "label": "GPU", "query": { "query": "label_values(modelName)" } }
  ]
 },
 "panels": [
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", modelName=~\"${gpuModel}\"} * 1.8 + 32",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", modelName=~\"${gpuModel}\"}) * 1.8 + 32"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", modelName=~\"${gpuModel}\"}",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", modelName=~\"${gpuModel}\"})"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{instance=~\"${instance}\", modelName=~\"${gpuModel}\"} * 1000000",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"${instance}\", modelName=~\"${gpuModel}\"}",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=~\"${instance}\", modelName=~\"${gpuModel}\"}",
     "legendFormat": "{{modelName}}"
    }
   ]
  }
 ]
}