radarr_api_key: ENC[AES256_GCM,data:fL3YWaIjJzL/zrIHpiAJzFYQYGHW8Q0UCyxkpnazMT4=,iv:kRgo/kBXg6J4o6eEDlqQO0NcJYP0Zf4RiJEBUILHIng=,tag:zrxVbiN/a654ZbxAHmAgIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbG5FNjhSTTdXSzlHRHZF
            ZEQ0a0E3M1BQcW1hMzl5ZTJoZnA0ajNaNFYwCmFZanZKRSt5Rmt5RWIydGJPZEVB
            d1NtNERuWWZlcWlMY1NHL0g0Vm93eVUKLS0tIGdzdWlBRjF2NzZoNm01NTM4RW5K
            K0JLREozbC9jQjJmb1V3ZkNpMHhaaTgKdgDpvVR4H8ygfxRiPB/l5dWndn4/AQ8I
            o4SwAx3I04xuvYa7CvJNtYw4FDumFU/pQRyqAZxXfdLxlApq+WcngA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17lsd78hka8rmuvmmx6d03cqjl2h55lsvrnzdfq0ge4acujf6nffswdwvr0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSEtENFhmVU5nRGVscWV2
            cUlJaEZCZ3B0RVRqY0E5NnhEbStDK25laEVBCjJtSm9KM1hEV1M1UmFMZFJWd3FK
            MjdXRjJobnNrZDVXeVpaZGdEZ21HOGsKLS0tIE53bkx2RnRpb1VOM2xQWDN4b2s4
            R2FtZWhwTHBCTEJwSkNsMFlMTE5TamcKcTG7TIXmlBFkGT0Jfqa20PUVJghOq1bU
            Lqkh9DqSNW6KTXSHTIHCA1h2ZGaNm+5lvPqZYjLcCVVmPrBgz0J58g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jmr8lvn5wmxv6w0lk3vapawljnqfvws095ale94mthcgxueza9sscqq3h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZTJLdFpXQ0lqbkp3bmdv
            VEYwNGxTam9uWlZMaE9iZk9ZY2dTQnN6SkNZCit2azNNakNpSS81M0gySTErcFRY
            dk1OeEk5SHVtNjg3R2dkeDlWTmtxUUkKLS0tIFpLcE1mcEgzWnA4YjYydTdzbzBT
            R0NVZlVFZjNpbWNBbk1RWHRGbENybVkKSKbKYhxSMKWx1B4SYYzrrUXvEO1hr7zZ
            iABm73QfWQMhZiA3aKgQNcqgdefDb296zANJr3hH/5NA9+DOklrsXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YzgweDNXa0lCc2JmS3V4
            ZEJDKzZWcGhRSWI3YUlWbGppNFR4SElEN1NrCkxERWdvREV2dzhSZUd1L1ViaGZV
            ejFXdWNoZVAyanB6VTRNK0g4VWgwOXcKLS0tIEFLY1RRb2ZjWXhsN3h1aG1uTU1V
            Qkh5WlZ6QkU2OWdyaVVwZHNBcE9PWDgKt6YpgurgaPlK0dKxRBCLDk4sstOqtXXO
            F5BAGuFRmGt8xsqycUkGHVVX/Rbv5agksmvGFDiJY6PBtl0UQy3dtQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUGdHWGprNlJvNTFCTE1C
            SjVIWk52cEZ6NVNZZFdBSUx0Nzl1bzdvTlJFCndadkh3dnJpTk9ncXhtR3pvK0h2
            OUR6TW9hSENLVy8rRWkvelFMMUo4bUEKLS0tIEJ1WHdCZFBGV0xzeHRPdm53RmZ0
            cjhqY2U3SWZmV0RjYjN2ZnNRRC9WOFkK0hLG7eXC590j383KbJ29h7OFrBxZZWyM
            zmrjrWy//jQxobLwu9rNVG3/wotYC/7kTJ2KN9GAVmg/2hBIZj1tRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cDZwSklPK2Y0bVRNMC9P
            VkR3TEFNL0lhemN1dXdEWlkvZ1lBZ3Z1VkN3CkJhanVqOFFLZEV6bEtPTnI4bzE1
            VkoxRDNLOXgzTmlEM21SckN2ZHVrY0EKLS0tIGhxTUFML05IcUgxSDJYYk1PWlJG
            UmpFcDBMWVcvNHIrSnhzU3ZUSGYyeFkKUNnNmSsW1G4HEVaDTtTFcE6vJnEbAjqT
            XyIm6E5AmnV32llVEB7uQ6PUVwMS3L5VVtqS9PG+Sivzu4heTL8IfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaVJHN254OExYclBZNGxj
            YmI1M2N3SitDNzJRL2hYWmsvMjdpWEZiRVJjCjVkWjZ6a2E1M3BPa2VVSFkyeXJC
            NDd1TWVpUEl4YVk4QnpEQ2lQOXYzUncKLS0tIFF1bjdVRWhTeUFxUGlmekVWcGN3
            V2lFK2FuUjJvUnJZWHVhOHpldUtsa28KliKve5k+lHmMdexQ6IuYbKtjrD/ccOBr
            E8Dq9EC71Gi2MpyupWGOlk7Qx6aNXNXEnFHd0NRXB108lZuhjgEH9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaUkvYjE5STN0bUN6TmFD
            UCtSKzJ0RzBCSm1PWnZVak1kOS9yREpHVTMwCnBmREJrV1NqY2RSWkxCY2RKRnkz
            ZUphVk1VN0F3Q2FUcTVhRXo2SDZFckUKLS0tIDRJRi9zbWVkekxmNXgzQ2MraDha
            Q3FpN1dnNWZIbHd4UUlGb1RZY0kyWGcKHE/zTgSlZ+OH5Nu+PreLE/TKnEKOj0tg
            Ww0xfgeaGlb2y0+1CNq4MBQ7T8+1PQdaYYWsmtPXAnpFLma341XpFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a4r3d5m0eu94vwsrse83k09fgclcfmthkz93p6h0m5vqyptq2yxswptzjf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeXdVN1VCeHZNWlFNNFJ4
            SnRSbm9HSFpWL1lnNUFaOUpKejE1VVBuMGtJClF0bzVjZlAyTFV6ZXFrdXBsTWtV
            cDY2RjQ0UUo5VFo0aGFtWUxhOFFCT2sKLS0tIGlLY3pXdmhJSlN2UzJnMXVaME85
            VjU2R21BaHBjQm1qU0dqK2twQUFXZHcK+adBoZYlSJs+eewDySyiIcDDvdLqM4mt
            45ULpFTlkUPalbc7jNdCCAkDSFtXp+geHKni1tx1+8fk6Wr5nj/niA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12yvljlgg94z8qfwyezz6mtmrpldxvfcqwzsuyfekszu296fg6upseeyc0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cjVUSURwMXNERjZjTjVH
            RjdGS0ozV3ZhZ1JESTRDaDJZOUVJOWtmZWljCnpBSVNySnQyUUNDOU1pNTY5dE9T
            YnNNbTdQNitSNFg3WVU5RUNua0RId28KLS0tIFM3ZEg3dnNRWm5reGFaL3R1dm4w
            SnlGRmhDL3VOaGpCM0VDK2NwajFRMU0Km0WTOUekSbyPFb/aYYvvDJEowCZ3p0sh
            UNAzumhqv3pCn0lz0XotyudeoTj1nddcVx9dUtt12uWS644DycT+3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-26T04:15:34Z"
    mac: ENC[AES256_GCM,data:tZu89i/gbe9EHK3g8obl7LCw02WekGqXGVbCcnypfuCj4/JeZ8qR3zlmAzjht1WJjii/ozPf3HcNr7BgsUcDh4gY+GOlg+uv1j4/R3tO5DR2fKQaK9ojMN2ydUjyP8R82LWIcqpgQkKRSc4FTuIg4iirnQw6Gw1mvtkqVyPGCIw=,iv:2mmPyhr113UVi1TdfCelcEu/3wVX2gdHnYWi0XEw0js=,tag:D7mqlfwMON36dJKZOHA7KQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
