{
 "title": "APC UPS Dashboard",
 "description": "Monitor your APC UPS statuses, such as blackouts and electrical noise over time.",
 "tags": [
  "APC",
  "apcupsd"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "UPS Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_battery_time_on_seconds{}"
    }
   ]
  },
  {
   "title": "Total Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apcupsd_battery_charge_percent" }
   ]
  },
  {
   "title": "UPS Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apcupsd_ups_load_percent" }
   ]
  },
  {
   "title": "Battery Time Left",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_battery_time_left_seconds"
    }
   ]
  },
  {
   "title": "Current Time On Battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_battery_time_on_seconds"
    }
   ]
  },
  {
   "title": "Cumulative Time On Battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_battery_cumulative_time_on_seconds_total"
    }
   ]
  },
  {
   "title": "Info",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "apcupsd_info", "legendFormat": "{{ups}}" }
   ]
  },
  {
   "title": "Nominal Power Watts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apcupsd_nominal_power_watts" }
   ]
  },
  {
   "title": "Last Selftest",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_last_selftest_time_seconds"
    }
   ]
  },
  {
   "title": "Last Transfer On Battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_last_transfer_on_battery_time_seconds"
    }
   ]
  },
  {
   "title": "Last Transfer Off Battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_last_transfer_off_battery_time_seconds"
    }
   ]
  },
  {
   "title": "Number Of Total Transfers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "apcupsd_battery_number_transfers_total"
    }
   ]
  },
  {
   "title": "AC Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "apcupsd_line_nominal_volts", "legendFormat": "nominal" },
    { "expr": "apcupsd_line_volts", "legendFormat": "actual" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "apcupsd_battery_nominal_volts", "legendFormat": "nominal" },
    { "expr": "apcupsd_battery_volts", "legendFormat": "actual" }
   ]
  }
 ]
}