{
 "title": "HTPC",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Plex", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Plex Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "plex_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Plex Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 1 },
   "targets": [
    { "expr": "plex_up", "legendFormat": "Heartbeat" }
   ]
  },
  {
   "title": "Plex Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(plex_video_transcode_sessions_count{state!=\"paused\"})",
     "legendFormat": "Transcodes"
    },
    {
     "expr": "sum(plex_sessions_count{state!=\"paused\"})",
     "legendFormat": "Streams"
    },
    {
     "expr": "sum(plex_media_downloads_count) > 0",
     "legendFormat": "Downloads"
    }
   ]
  },
  { "title": "Sabnzbd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_status", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(sabnzbd_downloaded_bytes)", "legendFormat": "Total Downloaded" },
    {
     "expr": "max(increase(sabnzbd_downloaded_bytes[$__range]))",
     "legendFormat": "Downloaded in Range"
    },
    { "expr": "sabnzbd_queue_length", "legendFormat": "Queue Length" },
    { "expr": "sabnzbd_total_bytes", "legendFormat": "Queue Size" },
    {
     "expr": "sum(sabnzbd_server_articles_success) / sum(sabnzbd_server_articles_total)",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Download Statistics by Server",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sabnzbd_server_downloaded_bytes",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Download Size Remaining",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sabnzbd_remaining_bytes", "legendFormat": "{{url}}" }
   ]
  },
  {
   "title": "Download Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "sabnzbd_speed_bps", "legendFormat": "{{url}}" }
   ]
  },
  { "title": "Radarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_system_status", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_downloaded_total", "legendFormat": "Downloaded" },
    { "expr": "radarr_movie_monitored_total", "legendFormat": "Monitored" },
    { "expr": "radarr_movie_wanted_total", "legendFormat": "Wanted" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_queue_total", "legendFormat": "Queued" },
    { "expr": "radarr_movie_downloaded_total", "legendFormat": "Downloaded" },
    { "expr": "radarr_history_total", "legendFormat": "History" },
    { "expr": "radarr_movie_filesize_total", "legendFormat": "Disk Used" },
    {
     "expr": "radarr_rootfolder_freespace_bytes",
     "legendFormat": "Disk Free"
    }
   ]
  },
  {
   "title": "Movie Quality Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_quality_total", "legendFormat": "{{quality}}" }
   ]
  },
  {
   "title": "Health Issues",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 30 },
   "targets": [
    { "expr": "radarr_system_health_issues", "legendFormat": "__auto" }
   ]
  },
  { "title": "Sonarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_system_status", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_history_total", "legendFormat": "History" },
    {
     "expr": "sonarr_episode_downloaded_total",
     "legendFormat": "Downloaded"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_series_filesize_bytes", "legendFormat": "Disk Used" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_series_total", "legendFormat": "Series Total" },
    { "expr": "sonarr_series_monitored_total", "legendFormat": "Series Monitored" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_episode_missing_total", "legendFormat": "Episodes Missing" },
    { "expr": "sonarr_episode_total", "legendFormat": "Episode Total" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_season_total", "legendFormat": "Season Total" },
    { "expr": "sonarr_season_monitored_total", "legendFormat": "Season Monitored" }
   ]
  },
  {
   "title": "Health Issues",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    { "expr": "sonarr_system_health_issues", "legendFormat": "__auto" }
   ]
  }
 ]
}