{
 "title": "NUT Status",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(network_ups_tools_ups_status,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "UPS Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(network_ups_tools_ups_status{instance=~\"$instance\", flag=\"OL\"} == 1) + 120",
     "legendFormat": "__auto"
    },
    {
     "expr": "(network_ups_tools_ups_status{instance=~\"$instance\", flag=\"OFF\"} == 1) + 110",
     "legendFormat": "__auto"
    },
    {
     "expr": "(network_ups_tools_ups_status{instance=~\"$instance\", flag=\"ALARM\"} == 1) + 10",
     "legendFormat": "__auto"
    },
    {
     "expr": "(network_ups_tools_ups_status{instance=~\"$instance\", flag=\"RB\"} == 1) + 140",
     "legendFormat": "__auto"
    },
    {
     "expr": "(network_ups_tools_ups_status{instance=~\"$instance\", flag=\"LB\"} == 1) + 90",
     "legendFormat": "__auto"
    },
    {
     "expr": "(network_ups_tools_ups_status{instance=~\"$instance\", flag=\"BOOST\"} == 1) + 20",
     "legendFormat": "__auto"
    },
    {
     "expr": "(network_ups_tools_ups_status{instance=~\"$instance\", flag=\"BYPASS\"} == 1) + 30",
     "legendFormat": "__auto"
    },
    {
     "expr": "(network_ups_tools_ups_status{instance=~\"$instance\", flag=\"CAL\"} == 1) + 40",
     "legendFormat": "__auto"
    },
    {
     "expr": "(network_ups_tools_ups_status{instance=~\"$instance\", flag=\"CHRG\"} == 1) + 50",
     "legendFormat": "__auto"
    },
    {
     "expr": "(network_ups_tools_ups_status{instance=~\"$instance\", flag=\"DISCHRG\"} == 1) + 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "(network_ups_tools_ups_status{instance=~\"$instance\", flag=\"FSD\"} == 1) + 70",
     "legendFormat": "__auto"
    },
    {
     "expr": "(network_ups_tools_ups_status{instance=~\"$instance\", flag=\"HB\"} == 1) + 80",
     "legendFormat": "__auto"
    },
    {
     "expr": "(network_ups_tools_ups_status{instance=~\"$instance\", flag=\"OB\"} == 1) + 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(network_ups_tools_ups_status{instance=~\"$instance\", flag=\"OVER\"} == 1) + 130",
     "legendFormat": "__auto"
    },
    {
     "expr": "(network_ups_tools_ups_status{instance=~\"$instance\", flag=\"SD\"} == 1) + 150",
     "legendFormat": "__auto"
    },
    {
     "expr": "(network_ups_tools_ups_status{instance=~\"$instance\", flag=\"TRIM\"} == 1) + 160",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Source",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_status{flag=\"OB\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "network_ups_tools_input_voltage_nominal{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} (nominal)"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(network_ups_tools_ups_power_nominal{instance=~\"$instance\"} or network_ups_tools_ups_realpower_nominal{instance=\"$instance\"}) * (network_ups_tools_ups_load{instance=\"$instance\"} / 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}