{
 "title": "systemd Service Dashboard",
 "description": "Show stats from node_exporter systemd collector.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "systemd State Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Unit State Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{instance=~\"^$node$\"}) by (state)",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "States",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Activating",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{instance=~\"^$node$\", state=\"activating\"})"
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{instance=~\"^$node$\", state=\"active\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{instance=~\"^$node$\", state=\"failed\"})"
    }
   ]
  },
  {
   "title": "Inactive",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{instance=~\"^$node$\", state=\"inactive\"})"
    }
   ]
  }
 ]
}