prometheus_sonarr_exporter_sonarr_api_key: ENC[AES256_GCM,data:YsZbBe4u8KLfCGCRkXLy6gtCm+m4iVdq+avFdl+juUs=,iv:GRgNoKB5yc26Z7egX9lPc7nOnZwz4YtO5j9/38VClEA=,tag:Gk8je9xdZVLNbvYi9conrg==,type:str]
sops:
    age:
        - recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMnNFMHNya3RtRW05d3p3
            UmJvWEorRXRIWnN2UDROYXVzMXQ0dDRzTkFRCjl5SGpHbDlSOTlWVGJuQm9ZTHNN
            NDhJSFMwYlpzVW45MWdsaE1MYm5rVlkKLS0tIHBNNHpSSUovcmNsSzRaaFNrcUZy
            THpZVXdDOTBBeVA1b0tDajZyNmJZbGcK3kcD3uXZS2ofWo8qYsAe/AOkQr1mOy70
            XuC7yLtM25aZLGsxniycNw/Pqt2BsniDQBLNZnJSbLl/mzo4FfNjXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g22ghnrdg858yv6w2ux8hgntj8gkdyjn28axdkmzyx38d4vx6geqj4px9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzLzREMVdIV2s1N3U3MnNB
            MUNZa3V0ZjlKOXh4a1pVdHZ2QTBuV0gvaERBCkZzRmJTd1FSdGZqR0RtdlUxK0wz
            WmRrWEZQbVJPdWZwOHhGOU85MnZiU1EKLS0tIDVVazQyM1k0eUlhdVhVcXJ6QkJv
            QnFXbGxYcTdqQlJxcUM3aXRoNld2QzgKj0r+uLnZu3e7GqLVgztHVbwaCsBFyeJr
            73IGQrqLQEqSnUFtO7p2mhAzZsTGSXcAORlUUWB9/PVsT3QTvHttdA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOHkvNFdGT1Q1WklxbXpO
            NFBBcy9lSUdxK0FYZGJuSGpCS292NVl0Wkg0CndYVHVrNWZvaUtYNkxVeVo1Y2VQ
            dDN5OVJPMmcvVzE1Y1J5b2x1SER5NlUKLS0tIGIzQU1JRjJrMG1oNlMxTk9ramRu
            QVFqZVdFVFdMOG1yZnZGOXdGWitOYVkKUjzaH/xIzL8Ps2V+qSJPX6N7BD1OFBS3
            pX/pTwBsFvwX0Hf24Q7zGL5hkKKMbu/reQz52wRYj8WW7Xsff6SH6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMURWQ21RTDU4TEN5Q0xp
            b0RnYlVjN09CLzlxWXoyNFk4bTg4QnhKRjBjCnErcVUrLzgwRzlyTHRucVF0VnRZ
            YWpKeisyczBrMlJBVXBHVTVlelZBejQKLS0tIHFZWjZ4UWZ1Nzl1bVVKNk1rTGRh
            UGNqbDExWWFlYVlzWkdjZ2Q4OStmMlUKBfMfxBkhP14/pe5ismQuFn9i11o811Jy
            niGCFVCqfvhJM6rdgWqLfpk3jjPxvKVJ4qu51UENAfD4zNoiWbtEYw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOStwQVozY2JHSTY2K1A5
            cWx0Z05mWWpmMkJiUTc0aHYrWjRRVG1YWERBCjVINjlEWUtKRzJlTGRkSEpSRDZ4
            bU4rMDcvMGdvSXVUckJoelVtc21tckUKLS0tIHlrc3RPeGp0czFyY0s4b08ySzdG
            c0hwZ29XVmU5bVlGcFNDdTY2SEpvL1kK5wKGjxIGquwgBKwFacR/mWctcqbJfSeU
            dz8nMRoYYFy4EVeKiOjXkvRBGeUnMrlUEWd6YMT5XXj5mxKa4SpfOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdnEwK2I0WHp6R0xTN0xG
            cWFEL051RXlHWjNJR0xhMk95MkpDOXhWd1VRCitudENCenJpSjE2N0JQSWFTcmkz
            Q3hYTGRPR3F5T2ZnZFM3VkZkR0VUVXMKLS0tIFhKVFdoZHJ1dFdxQzBCaytiNC9W
            N1FWUnlBUUpOV2RNdUdmVUNjMWZtZ3cK2D18XvdkJphkbpxcg7qxQIfOKj+D0/On
            pfFrSDPxfI6uYuSSYrLYJRuWSnlQ/j3SV58OBDjBI91A3PqeKV8vPQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYM3MwdnJDQnd3L0xQcHFp
            Yk45QVRjUUhmRjNFR0hXdXN5THJ0NVpQYUNVCndweFVkejUycFJtb0F4bk8ydDVv
            bzNwUC8zWUw0b0hpNmo4alpsK3QzdjgKLS0tIHIwTmxNWFlhUHVlZFFCL2diRTF6
            WW9xOGxjdmRUeGpQSkxpRlFWcHVXbE0KVms3mLvaP5KLiVb7xgiGxnKIzlVAXBd0
            pM+z5WWZjTXXFwHOM+shyru25zHh56P73ymaVC98qS9+gB0FstZ2JQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x708x83pjj7urp26pncx67fqz8a3htrf0umw7c00pvmxhl6y95lszjgd6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYXYyWmVuZ0ZhTS9jN01p
            ZXBzSXl1SkxqV3lFTzJ3RUxoTENBeUo4QlRVCjVidmdoMXErWFMzeThyUjVKTG9o
            MGJwMHhPazJtRUlYY3RvdisxT01XOEkKLS0tIDVKaytUY0ZnMlZ5OERBY0EyTmov
            SHhmL2FrVHdUaUJMOWg2bFpLdEdHZzAKEcMBEt/+ESnf6GRk1IXywFPgxaP/5NOV
            L4kfVea6nu996Xde1oBL5rq6859BRGyZTVnmoUfsTuG1fl/aJ8An4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T03:26:38Z"
    mac: ENC[AES256_GCM,data:jsjrvwGnluKyYzbAYblNvT4u6TXwaXC2FQSf8OycSeGkdaQImBnCTCk6aBvoMnqevWNkJBCojBTRfbrMXwVDV3UTFS/qkwHXWtsVksXKRvC0Ycz5Ptbpe6S7BQfU9EFYCKLB97rUxYITgnrPOSsZYmLe7iwtQPIvfYcFAGZ8hJE=,iv:DDvP+QwU/MQPGxDtI67AcANWPrmSsZyCNrsYmPbA6nM=,tag:IrALrNd9XOAwEMiaZoVcaA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
