{
 "title": "Borgmatic Backups",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(borg_total_backups,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Backups",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "borg_total_backups{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total deduplicated compressed size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "borg_total_deduplicated_compressed_size{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "borg_last_backup_timestamp{instance=~\"$instance\"} * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "borg_total_size{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "borg_total_deduplicated_compressed_size{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - borg_last_backup_timestamp{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "borg_total_size{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time since last backup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - borg_last_backup_timestamp{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Backups",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "borg_total_backups{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "borg_total_size{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Deduplicated Compressed Size",
   "type": "timeseries",
   "description": "Size of repository on disk",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "borg_total_deduplicated_compressed_size{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}