{
 "title": "Borgmatic Logs",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "Data source", "query": "loki" },
   {
    "name": "host",
    "label": "Host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Started Backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({application=\"borgmatic\", host=~\"$host\"} |~ \"Started backup\" [$__interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Successful Backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({application=\"borgmatic\", host=~\"$host\"} |~ \"Finished backup\" [$__interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Failed backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({application=\"borgmatic\", host=~\"$host\"} |~ \"Failed backup\" | __error__=\"\" [$__interval])) or vector(0)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Time of Last Backup",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (count_over_time({application=\"borgmatic\", host=~\"$host\"} |~ \"Finished backup\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Most Recent Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{application=\"borgmatic\", host=~\"$host\"}"
    }
   ]
  }
 ]
}