---
- name: Remove Proxmox VE Enterprise repository
  ansible.builtin.apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise
    state: absent

- name: Remove Ceph repository
  ansible.builtin.apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise
    state: absent

- name: Add Proxmox VE updates repository
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
    state: present

- name: Add Debian repository
  ansible.builtin.apt_repository:
    repo: deb http://ftp.us.debian.org/debian bookworm main contrib non-free-firmware
    state: present

- name: Add Debian updates repository
  ansible.builtin.apt_repository:
    repo: deb http://ftp.us.debian.org/debian bookworm-updates main contrib non-free-firmware
    state: present

- name: Add Debian security repository
  ansible.builtin.apt_repository:
    repo: deb http://security.debian.org bookworm-security main contrib non-free-firmware
    state: present

- name: Update APT repositories
  ansible.builtin.apt:
    update_cache: yes
