---
- name: Check for omnibus storage
  ansible.builtin.command: grep -w omnibus /etc/pve/storage.cfg
  register: proxmox_omnibus_storage
  changed_when: false
  failed_when: proxmox_omnibus_storage.rc not in [0, 1]

- name: Add omnibus storage
  ansible.builtin.command: |
    pvesm add cifs omnibus \
      --server omnibus \
      --share proxmox \
      --content backup,images,iso,vztmpl \
      --prune-backups keep-all=1 \
      --username proxmox \
      --password {{ OMNIBUS_PASSWORD }}
  when: proxmox_omnibus_storage.rc == 1
  changed_when: true
  no_log: true
