---
- name: Check for omnibus storage
  ansible.builtin.shell: |
    cat /etc/pve/storage.cfg | grep -w "omnibus" | { grep -v grep || test $? = 1; }
  register: omnibus_storage

- name: Add omnibus storage
  ansible.builtin.command: |
    pvesm add cifs omnibus \
      --server omnibus \
      --share proxmox \
      --content backup,images,iso,vztmpl
      --prune-backups keep-all=1
      --username proxmox
      --password {{ lookup('env', 'OMNIBUS_PASSWORD') }}
  when: '"omnibus" not in omnibus_storage.stdout'
