---
- name: Check for deploy group
  ansible.builtin.command: pveum group list --output-format json
  register: proxmox_deploy_group
  changed_when: false

- name: Add deploy group
  ansible.builtin.command: pveum group add deploy
  when: '"deploy" not in (proxmox_deploy_group.stdout | from_json | map(attribute="groupid"))'
  changed_when: true

- name: Check for deploy ACL
  ansible.builtin.command: pveum acl list --output-format json
  register: proxmox_deploy_acl
  changed_when: false

- name: Add ACL for deploy group
  ansible.builtin.command: pveum acl modify / -group deploy -role Administrator
  when: >-
    proxmox_deploy_acl.stdout | from_json
    | selectattr("path", "eq", "/")
    | selectattr("ugid", "eq", "deploy")
    | selectattr("roleid", "eq", "Administrator")
    | list | length == 0
  changed_when: true

- name: Check for deploy user
  ansible.builtin.command: pveum user list --output-format json
  register: proxmox_deploy_user
  changed_when: false

- name: Add deploy user
  ansible.builtin.command: pveum user add deploy@pve --groups deploy
  when: '"deploy@pve" not in (proxmox_deploy_user.stdout | from_json | map(attribute="userid"))'
  changed_when: true
