grafana_secret_key: ENC[AES256_GCM,data:C7us+mvDy0aCw/I32l9m5l1GfzE=,iv:tUc9SaEleEf+6AopRYoPD71418A7Y4Baz9dRUWfap2Y=,tag:4q8rHjiWmPPf1VnWcT6WyA==,type:str]
grafana_to_ntfy_password: ENC[AES256_GCM,data:mTTm0E45,iv:GTlgVp8yYzWeT5X7nCNXYcS/wzUXyvBGu/e+basldz0=,tag:wwH7e7vKgGb7PT+sOUjvug==,type:str]
grafana_smtp2go_username: ENC[AES256_GCM,data:dFeSxRCeNeI=,iv:XrHVcA9xjbHLYkzm73+p9iMkjxezQV2EJVTeW6Mb8Xw=,tag:4K7Kwbn8TbwFNfGuHnlvog==,type:str]
grafana_smtp2go_password: ENC[AES256_GCM,data:lW0uys2kxchliQxYh68WBA==,iv:oEQeebxpI1Olzj3t/u/xR3T915wV+vIid1N3KWkDQSI=,tag:grYBXUW/eigzaYILtakK8A==,type:str]
grafana_authelia_client_secret: ENC[AES256_GCM,data:exy2MlEvHWkjzQJu+Cg2LjJ5tC+bLPzv3jRfUYNi5JVwcXn5j/JBw36BVv/ARZMsCGWRBmWFmIooabXGD+IKQFokbGKUC1at,iv:IOrBlstRk/vEnFs9CV7XmvV162eBtD8iQgkJRum3qpw=,tag:dOe+lk+5tii6mPXaGUZapA==,type:str]
grafana_controller_mosquitto_password: ENC[AES256_GCM,data:3YaEMZ/wR/+zLqJHN7OYErd60Rom1TfMedZAr7cNY/XMVu8fsgFjwTKZTWx1W5UXTZrgZrmXjV0kTnApUFlYGQ==,iv:OZOsxrT1VbL/WhQiipnqZ/ac/94H/1YdgIOWEOJ2dMo=,tag:wktDP4ZbU4RFQ3LjGZ0DWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZVd0MWFNR0ttaUYzRlBp
            Sm1PZXJIbEc1U3ZCbjQyTmVEZTE3R2hMVXhJCkVtbXdnYkUzaUVhREhMZzJpYlQy
            dnZGODBlSWJwdldiYU1ac0p5ZDQ3V3MKLS0tIDdpZDdHS2NxYlB5VklRL1VVNGsx
            OVVSNXEzUGphazViZW5EYmp2ZXdVdWcKdKh8ePOXXw0Qv8tf4SIDuelN6tIysFDp
            a8e/3Qazpat+AwrOY2LtcRs84H99/ptobtJZPpHPVg6R3AASNA/SkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZDRIQ3RXSFRSNDZmVVpF
            b054NW9ySXNvZis4OGEzZWk2UlZaRlo3NGtZCkg1ekNSSmZrNmVYaFAvNDhiRkRJ
            MGh6WHpsSFRPVGllbUlidFM1b0pXSUEKLS0tIE1sWHp6SktueW1UQmNJMUNSY2l3
            ZkR2Rm5FNTRyTzc2bjkzT1lHZHRtYmMKlQEe91JxBs6u+mAu/VFbdorqDJhy5cKl
            gzQn4U0oMF9QINsz30ai7enXha5TUETAQIi5SeeZRxcj0lr84rjd7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g22ghnrdg858yv6w2ux8hgntj8gkdyjn28axdkmzyx38d4vx6geqj4px9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWa3pJWTBWRkJlKzF1eEVO
            L0ErRlFqYkptYjRQbHZaZTNRRjJtYkdFdVNvCk1xR3ZNTlFSaXVoMzI3Q1I1ZHM2
            Mmd5bGw4SWVCdGp5QXpjUE9EU0NCa2cKLS0tIG1rSm8vNThsSWp4RUxDaE0rN1JH
            WUtPMnNxQk1EZjluZ1NiVkRFT1grcDgK6v8x+dsf2y95smGWzOLnRVwly+m0Ys65
            +fwk2UeSFo2TP5qMAFMnEhUuErxT5hAJmVoG1Gv15pAAhonXWfgnuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWDBMeituSjRkcVlMQUNW
            K3YyaHUwcUpzZzRrZStwMFIrN0x6T1lQdER3CmxrdE90Yk55YzVZcHdGVzJmcENn
            b0lUajJRTVRDb2toNW5qMXFqVmlmVEUKLS0tIFVoK09qUi9ZSWpIZ1ZoUmdGY0FF
            R1RNYjMydVZWOWI5eU9VL0NwbGFmeWsK6CF5F/67xR7iT5HSCkeNynPQrVEKObUM
            7hx/+2Kqjv6tkgLfdbavRP8QWKcTkqeriybRogPuxCp3C8P3CDHhbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZXloeWRBK2ozK2tVV1RG
            Z1k0bU5odFR5U283a1dFVlF0eEl3UjYxMDNVCkQ2eEd3SjdDR1ZVbENFa3BEdU1i
            cUxtSFArNW96QlkwSVZ0S1JvUjgzd00KLS0tIGVXb2hsMksvaHMrcWM0czRvcEhQ
            T1BWNUZuVUNYSVhtMXhOcEJjTmNQYUkKhPdaKJnj0loMyX2+v+ByOIbWRZEAYtZT
            ZrJIHibQN4GwHUTjHKMmuSBqP/0fCmAHyKDHMRx6eU3cpR5xjmfVMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UXEzbDJ0WVpwUXduaFla
            ZE1yMGE4TDVGVGtHTFVMcitvajBPOTZ5TFhRCmNreGtycjgwVjI5Y1EwN2lyamV6
            RWEzaTh4akQ0NFdxWHlnVTRmS2xYWkkKLS0tIFJ5MUxrNmV0NzFEQnlxWTVML285
            Rk15RnVxQjB2T05XZ3B2NitDakJleDgKLryezSaLhjk7v055oza9vSSXnqmf6S0p
            nhJvl0Fifq83BNKsoVGa4B3v8UjdDF7pTqJrM2cR3vW8s4OjyyANCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TU9SYzU5VjVsQjd2ZkU4
            dnh2Uk01aWo5QzdKQmhBYmdEbkpmL2tzZlFvCjd1emdicWFtOW1DWE85UVlYa3RY
            YTRxZGRvTStZYnBpR0NiQ2hmL3MxaGMKLS0tIDNybGlUNXVYNzJyQjIxd2pIcU4w
            blV4UHJLNDN3OXAya2Jtd2tzUmFySGMKot5ns86YPVQnZiBw5ShfYMEzpr/G3s6z
            zYPamvviCNpfInCBwmFFdS9sBM3MsBzkvTvm04Rr9tyBuNS0jBJMmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MXZPamNlT0VMSlNKbnl1
            MUFZcTVzbGlqalZ2czZLbDV2ZHkvamVKTEVvCkVONWtUc0ZBSE5PQ21oZG8zYmlP
            MkpsK3NZeG5JdHhQT252bDltZGQvcWsKLS0tIEwrS3RRQ3BWbkpIOXh1cVNlQUsw
            dUFlbGVYNGlZMStzZlI3NDdhUkRyalkK4H8yaICWaZo/3pQMV/xO1J7M9srJyCR+
            jm6ePYwMCK1wBJSCdUCy7STRYl2FphyDTVUcm4OjQw4EgghE9x9dzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x708x83pjj7urp26pncx67fqz8a3htrf0umw7c00pvmxhl6y95lszjgd6r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGb0pWbXFzSE9xNHYzY0Rp
            V0FlRVRIYlRFVS8vakVmMXVlZjU5dEp6RGhJCmVqQXZ2OVRiNmRQRGp3WWlkVm1l
            Y2FxUjRWMm8zTVlldEZaZWZuRlNudVkKLS0tIDZSSVZET1pUSnMydFR3WC9KUkN1
            SmdBa254Ky8wT3F3RFRBQXl3a3J1cGcK111fv1LZiMbu3M7g0rR06Gk0af5f4oL9
            bOPCHyriw61NSZC9wIn8J32/PAJD9yE45EM5povY1M5wZFG7uAMFpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12yvljlgg94z8qfwyezz6mtmrpldxvfcqwzsuyfekszu296fg6upseeyc0t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVc2Uwd0tXYll4SkJLd05w
            bUZMZ0VtTUNTQ0cyU201NjAxVGhsaDFwOGkwClRiSndPbUFMeWZ0M0JzYzlVT1V6
            S0hOV0pJYVhjTkVnVTVwd21XVFJ6MFUKLS0tIG95SWVHVTUxT2FQQTZvbTZYWFVw
            c3dmenBjdGhjWE80cTZWYzVMOWd6bmcK/pjcq63bevUG/oxrpTtRj7WbLaDLP4eL
            D/eZUM11Lv9Dkj91w/g6KVN+9ZYlrzN+kTJDeaeBuS2Z6/cyfqnWGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10zakwy8z5448vj7ur2h7vn8wfzvt2nxwq4pk4wx6cs34mlg58yasdjhc7l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVGNYSlJyL05sUG1jYnlJ
            YU5mZTlBQmU0c0tLcWJzWkJmcEgxakV3MjNjCkllY2Iya1Exc2hoUjZlblFuU2Nj
            SVg1bEtHYWE1SWFweC94NlRZYnpCUzQKLS0tIEY2MDBXMXR4MUJJcTdOcUpNU08z
            RVZJQWs3YkIyQW85VHRWZlpzSmdnaEkKO8MfqCjXYqzNgNpXt9pRb4VJRMkKemCe
            XV7LKBY4JbU3E8DnNr3MCTggD4rYS9uDOMMr4QWXvqnHETw7YtrjVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10q5gqw4gwts228ayanvalq7c93peqjdsfqcgevd7qr43u5rhnczs9u2ysj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwY1h2N2hKbytjWklzdEpX
            ZWNPWkpYMncvTzhyUGFVYitmMi81YkxjeFFZClU0bTlHazZrTk5pQ2o5eUhhNldS
            N3R4dENaeVZtc1RjOTc4Vkc1WDNSeTgKLS0tIGpwZjNZN2w2V1dqWFdEVklxc1dR
            aHpkbGduakJ4MnFJOU84aHZPUnBNTFkKkdSPT4LZtA7v2aJYiSm6zztcAGoccLp5
            lBhZt3w+ub3EcB395BcdRuqdr8w008buPLbDclAVo57lQl0DvQmYrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hxynjkmtgcu9lwejchkjfqjp484at589sznqkxk6weucp37p4p7qaj440h
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eURQTzZzKzVHeFZMcnkz
            ZEN3SzJucmJOdFJ6a3B1d0Y5SHEwL2QxOGwwCkVSQUJzdkwzbk1zY2NRWHVSS05X
            UG41dU5va1I0YU11VVY1ZUtmTFIzNXMKLS0tIHI2dVk1YUY0YVRYVmNTcG9XNVhM
            RzF4elVQOG0yN0xaYW9sdnd1RDJUcUkK1CHDljG+Q0Iayn4DAVr64qOzlj1MNWK3
            OGFToias7/29ZPtWu1uPwSgjqJVMsSw1x0K1R1U2iqNh1XTDokkGyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dtf3ahstj5mhzcqf4d2zc54d5dds69ka32dqpmpsskyaz04dtshq9ryxat
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZ0d3OGZZRXBsaThqcXlh
            K3pSa0I1aWxGaGlEazdrUGRjdG5JQzJZT21jCms3Rk43OTRKNkdjK29nY2V1ZkFJ
            K21yRzZuUnU1Mk83SGxyOHVKTnFJekEKLS0tIE5uNHJzQm5zTitHazAxamVJZVps
            VGxVYW1qelZOamZwOHdtdEtBQ2FoRkkKVoxZ2xE+0u20z/6g+z+1R/R6UrcCAXZe
            jc5fpiiTAF8XeKGocbn6Xut0yavQyNw3vAsGvGS8oajoHWCjkqf6xQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1px3aq87zcjgts5guc59fqn64zjkqzukdwce4a0ggza83n3atkcws4h5aww
    lastmodified: "2026-07-19T19:38:14Z"
    mac: ENC[AES256_GCM,data:49+G6veG0KG5Di6R/Rsn2AUZiGUyGv4doLBMgjV/RokaNwCZ0qIVkGEIjVbh7AebbPFkOBMTVJLBUK/vUn2PqPIcZ4XIuKtn1Ftk+UiN3CjfjfZUg/jGo/gzmtUTSqzWbEV7sYg43v+6r06Y/OUQCpbnMWxZhrzYEhAMl3Nihvs=,iv:CKjP08+9NKbh0ZeItgwF9SVSbCS3mn8oWdRM7V+ZQAU=,tag:vd+ZirfR0yuHZPrcSuhCaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
