grafana_secret_key: ENC[AES256_GCM,data:C7us+mvDy0aCw/I32l9m5l1GfzE=,iv:tUc9SaEleEf+6AopRYoPD71418A7Y4Baz9dRUWfap2Y=,tag:4q8rHjiWmPPf1VnWcT6WyA==,type:str]
grafana_to_ntfy_password: ENC[AES256_GCM,data:mTTm0E45,iv:GTlgVp8yYzWeT5X7nCNXYcS/wzUXyvBGu/e+basldz0=,tag:wwH7e7vKgGb7PT+sOUjvug==,type:str]
grafana_smtp2go_username: ENC[AES256_GCM,data:dFeSxRCeNeI=,iv:XrHVcA9xjbHLYkzm73+p9iMkjxezQV2EJVTeW6Mb8Xw=,tag:4K7Kwbn8TbwFNfGuHnlvog==,type:str]
grafana_smtp2go_password: ENC[AES256_GCM,data:lW0uys2kxchliQxYh68WBA==,iv:oEQeebxpI1Olzj3t/u/xR3T915wV+vIid1N3KWkDQSI=,tag:grYBXUW/eigzaYILtakK8A==,type:str]
grafana_authelia_client_secret: ENC[AES256_GCM,data:exy2MlEvHWkjzQJu+Cg2LjJ5tC+bLPzv3jRfUYNi5JVwcXn5j/JBw36BVv/ARZMsCGWRBmWFmIooabXGD+IKQFokbGKUC1at,iv:IOrBlstRk/vEnFs9CV7XmvV162eBtD8iQgkJRum3qpw=,tag:dOe+lk+5tii6mPXaGUZapA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRGNWYnRzeTQ0VlJhaW93
            WU5vRUc3MXQ1UVc1bzR6eDNURW51MVljaVRFCjVXUGQ2ZFZSL0ovVUFHTjhHOXNV
            dS9sQlFaMGpLREw0VGZOY3lGY3lJRU0KLS0tIElZZjR6b3RIZzhFeVRhWFY2Y2x2
            WFBDcXFuS1B3V2c0d3FqSXVPamJvb2MKVxKI7LRlDXm63/IL2Ed7gE4joxl8TzIT
            5umUb8K6aIW5mfq2EBq9c+YjzRS+FJSKaPdTL4686j2wJ7UwvQklyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0V0xWUjZtRXc3RDByWWNK
            byttbHk4QVZNTkhQeFR5aXhqeXg5emFLNDNzCjJONS9kMkJBckR1VWViNWVocy90
            OEUxcHUvV0FicVRmMCtZcEdxQmtYcmMKLS0tIDE3azRyampUSUFRcGs5NmhVWDl4
            TGJsSXIranBES1ZYWEJKTFdYT0xSd1UK40KGKfl6YoypRyS1Z1CG37mgGolARCWQ
            0kAcABGBHPzXpYfnFSmcit5XWvfO7+g/Q377YuHjugnWL/4Epl/vdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g22ghnrdg858yv6w2ux8hgntj8gkdyjn28axdkmzyx38d4vx6geqj4px9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6R1ZYakFYaVpaWndNN29l
            Wk1XNUYxb093bDlhZFgxS0o4dEFzUXFVUm1NClQ2ZGNMbVViak5YRldSbVloeHo3
            ZUNQckpHaEJTUTQ0eWQ0NEhQNFpoTVEKLS0tIFJQS202aUpEcWtmaXU3eHNtQzk1
            ckdNVFVjSkZOTG5LQkRkWVZVUlJKQ0EKJcNP0b9HFhueWpFL+G5l42jOE63FJ3nE
            YAaARX5AbhoytB9177Zt2qGilrtwHBw5ce/27v/ut3AyJ8MM725uSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdUhFQXM3aDU1eE9zRkgy
            MDRpRU1yaGpxWGozS1J5M1NWR2tzemhEM0J3Ckl5QVZ0R3c2NmRXMEVqTHpXWHZu
            QzRqdHRZOHBZSVRDTTdjZzJWeGx3OWsKLS0tIDJNQ2FNMTg2cFJYY3gyRDY1eDlH
            SnkxSkV4c0tWNEx1eW5RUFlRUEtGRlUKRC9wUryEmY9Wr2vd/t+7Dt/GOXwMPB9G
            TLjMWK5NyMBqaKSrvGZhfjm6RWtVFECZ1weUpnNNtgJcUpgM1knNEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnK1VPUWVhZGcwSEhiOXU5
            cUNMZEVCZEFBL1lOV1RjcHNRd0ZXc1VYV0Q0CkJBVDYram5BNzZhT0w3QnRaNkUw
            QUZqUDEvRVhhcW0weGM1NEJjK0hDZnMKLS0tIE4yL2Qwb0hNcEVqWk5vdEM4eUIv
            Y1IrQTdLNkRHK0tRaStqN21QTmZueTQK/FN/YgBEAEq2jsCU290ZkaE1uF6997NY
            O9I6JQm2avn2jzlowc4cQtU/QUE3oTDsqgYlyFejEhn8YewRWp80Iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJL2tCamh1NU9LaDVQeWRk
            bFBneHRqdmxseG5Ha3hsTnB1YlVVMVRRbjFZCjRLeEpCWDJlZzlHQ2M0WDBtcmRI
            d1NYb01QWFFFQVFUOFRlaXdSdUIyTUUKLS0tIDFjSTk2ZHJycWJONnI5WURSQ2g2
            TmJhaE40RFFzTzI5anZFUFdGWHRpeHMKOPDj0KLsef9HGtxrPiCI2/ZVVZDcYDev
            KO/JlkVj9Cc3gXu5XR8Isvuvhx4XjQPbGLHjjI7XNNCiG0CpSSKwjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaE84K1pOUWE5K1A2OEVO
            WUpQcGljenpGWDJiSVVlYnBMRTF4eUxZRTFzCjRTc21IZEZReEVVcDd0ajZESUY5
            QWVjcXRoS1k5dFpob2FUVE95QmE4aEkKLS0tIEtINWV0dk10ZGM2SFYrcjVQVjZu
            eVpqUE9maS9VMVZodjNkMU1UQXQ3RFUKUIxXsvjEqzZfw85fLxLVXNNRWW1h7LCT
            +jKPEYmX19dgAM7t15b/WyB73eFftkpDY/QlGD7mXVWc4Zst+emrOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMkkrbW5XUUMra1ZjMCtP
            ZmZLQUYvVHFuVVlaVzJ3V3pqZXF3R2x5QkhNClVTdk5aYjZSN2lwZG56dDlQV0lS
            ZE5FdXpqNG5DMUtDZXNzTjErd3FBN2sKLS0tIFlCL3ptL2ZocFVZSklINGg3ajFY
            b2l5Vnd2c3VkV3RnSmxxNE8va0R3d1EK8+cuaQeLZuIe6nzi2d+LEZnJQiRrEuhn
            O9Yzh/GNiJGL15GTJ3zKbEs//3M1jFr+MngVS5KXXw2UJkQQteCn2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x708x83pjj7urp26pncx67fqz8a3htrf0umw7c00pvmxhl6y95lszjgd6r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyV2I3RjB4QW9RS215QS9B
            Z1ZjK09GL1NFV2JjVlRtVjdITi95aTNsSkdBCnl6RkRsMzJwR2k3L2VROHhQbmdq
            Z0pUcnlKSVorbVhLc2J3M0Rxdkl3TWcKLS0tIFRYZHdiOFFUeVBlYTBDWjh4UUMy
            bGNMQjhBWE9WV3pCeU1kbXV5NUhUSkUKG1Cf4H2cxMqBepuuQHEoudYcyYqqS7It
            2GQZWlCxjhm7tdZb/koVq+jt9fW3ed6aCBnlW2fulqUNiGDS8pfDxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12yvljlgg94z8qfwyezz6mtmrpldxvfcqwzsuyfekszu296fg6upseeyc0t
    lastmodified: "2026-04-19T17:16:09Z"
    mac: ENC[AES256_GCM,data:qd3hAdJ74BFe/vPYc8x68hHBDyE705wD7xRxvD+2NUbKn5bUs+9jb31ky5fi80ymCUouhRUKc7tkZm+kY76jY2jfwJtRWEywIRYCwR/xWJQFQdU5K6wk1l6WLCOFGk3uV+KtE9eymjlxYGANOKulZVAR5Q/KX+Rl4YhPPwkII6g=,iv:HsO8gRJIiDkqGsDp0XtPGnPIxltxKczJShvkARLP1m4=,tag:RkJkgZkHYrvP3UZ6kL9upw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
