grafana_secret_key: ENC[AES256_GCM,data:C7us+mvDy0aCw/I32l9m5l1GfzE=,iv:tUc9SaEleEf+6AopRYoPD71418A7Y4Baz9dRUWfap2Y=,tag:4q8rHjiWmPPf1VnWcT6WyA==,type:str]
grafana_to_ntfy_password: ENC[AES256_GCM,data:mTTm0E45,iv:GTlgVp8yYzWeT5X7nCNXYcS/wzUXyvBGu/e+basldz0=,tag:wwH7e7vKgGb7PT+sOUjvug==,type:str]
grafana_smtp2go_username: ENC[AES256_GCM,data:dFeSxRCeNeI=,iv:XrHVcA9xjbHLYkzm73+p9iMkjxezQV2EJVTeW6Mb8Xw=,tag:4K7Kwbn8TbwFNfGuHnlvog==,type:str]
grafana_smtp2go_password: ENC[AES256_GCM,data:lW0uys2kxchliQxYh68WBA==,iv:oEQeebxpI1Olzj3t/u/xR3T915wV+vIid1N3KWkDQSI=,tag:grYBXUW/eigzaYILtakK8A==,type:str]
grafana_authelia_client_secret: ENC[AES256_GCM,data:exy2MlEvHWkjzQJu+Cg2LjJ5tC+bLPzv3jRfUYNi5JVwcXn5j/JBw36BVv/ARZMsCGWRBmWFmIooabXGD+IKQFokbGKUC1at,iv:IOrBlstRk/vEnFs9CV7XmvV162eBtD8iQgkJRum3qpw=,tag:dOe+lk+5tii6mPXaGUZapA==,type:str]
grafana_controller_mosquitto_password: ENC[AES256_GCM,data:3YaEMZ/wR/+zLqJHN7OYErd60Rom1TfMedZAr7cNY/XMVu8fsgFjwTKZTWx1W5UXTZrgZrmXjV0kTnApUFlYGQ==,iv:OZOsxrT1VbL/WhQiipnqZ/ac/94H/1YdgIOWEOJ2dMo=,tag:wktDP4ZbU4RFQ3LjGZ0DWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYmNRNXNvdXV4TVhubDdH
            VVdOaTRVbTNIemJJZWd6Q1pIVzJFM2wweHlnCkdnZWtqTlNUckl6Q2ppMjlvSmRU
            bDY1RTR0RCtObndIMjk4UElTalp4YWsKLS0tIEZLQ1Z5b2NlQVRUbE0wVkdsRDVV
            SmQzQ3JCbnpMU3ZrUjJlMXdjQWk2OW8KgCH7QncJ/jZSvqtBa0V1Rn2jHigJfJV4
            e4Upms6cUhWFZl8/zfdFR1pT6lBtVshKaNSttXwayAdfD0pZaDYfeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTDRNNithRFBBUG5HZnhN
            YlZRUW5jYnAwVytncE10S0pPWVZRZE5kK3dzCmFJTkpVaVVUR1FHY29HUWowejZY
            RmxhRTdlYjRzQU5kVmUvZGVlMmJjazAKLS0tIGtLbllEREZjclZoVVJaYTFqbUpm
            M3RvQ1FMV1V1ejVjc1FVSERvQm5uZFUK1lISP5u+jNmJoi1OG9zrrl3vPmIUDVmq
            y+7UqFJHiIwqzXkRxAcQgChk75GXcwfSO2VOSGrdFmgF5bW3mjiK/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g22ghnrdg858yv6w2ux8hgntj8gkdyjn28axdkmzyx38d4vx6geqj4px9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bkNWY0dRRzZRQ1d1eWJk
            MTNpUWRGZ3lFQTh0bWdTL0V6ZjlqOHVaOWxrCndGaEFORVkwNnVSWGVOdkg4SVd5
            OHBxdlJnQzBjVXdzM2FhNi9yblplcmcKLS0tIEZ1eGMyOHVwd2hBc2pIYVJ5R1cz
            dnBhN1FyMy8vRDBJNWUybStOZHRHQ0UKXaMUJrM4Wu/QDXy/fDxoN1q2EMIL3rCi
            CNy1WwB7ZSsEDonu9THcCm7Nwq4mI8IPmljpJP1NurnhbywqmxTkew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cXhSMmFjZklqMno4emhs
            YmpUWk8wdlVKTDR0bFhiMkJKMUk2c0dDYVFVCkFlRU5kWmNSY290Wlo1b0xwMC9S
            ZG9EVVFDa2RJVEpEamYwcUdDbDJjTncKLS0tIGM2SERkalVWa0ZIUHZ5aVpVVGhk
            MzloTkxyUVRzNkFlcHdCOUxiaEVvdDAKOvOAKaAQfZVxaHAxJIggKc3zaUmIUXVl
            mVrMuqd6ge8kWvDTAyK3IMQnriI1q71qFlRDUsABE+KAf8QWjMf0+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySE9jdWZ5NnBBaEV2UGtM
            OEZITThkSEtPaWFmMTljZ0dCRzFXdDBMRW5vClg1L1l4d3RsUlBOd0NQSS95VWox
            MHQ5TS95ZWI3c2ZvSjA4UGNXQ1lCV2sKLS0tIDhlZ3l4cGY0aUF2dXI4UmlZWEpi
            NWpnQyttdEpqV3g3SW5HYmJLL0dTVHMKrw7lvRAZXnojbcXxq5MaXZDOdWD4LT2a
            H3fayPe7yA8+/RbcKqzP98EUKfmxWTAe0Py9Aoyry9fh22t+0Y//RQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SC8xZzh4MEtiNDhQK0RX
            YkNCYVZkYkNhS0VqdmgrRklJTkdoelBJSUJZCjBoWjVWbmVuRVBucnNxQ3kxL05E
            bHhtSXNrb2pPSGdTQ0p2N0pVbWJkV0UKLS0tIEM4NXRYZ2lWTTVPdzM0RWp4NmZ3
            eDFhUU5rTDY1SW51elgyeXJyM1ZSRG8K7EQoS6PhPpH9kKrLgXCe1Mx4CCEJNumW
            4cRTKEEFlV/yLtszOuk26O6M5PlXi8OINPBx0wknwwTdF77EI4FfxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RmFZSHQ0MWlTQXRmSkRD
            NmtOcXNHRDB5aWNCVU9LRTZUUDdvbFFFbndNCkcwSkV4WnYwYXc4MG1yUnFLdmlk
            YktNMzNoQWIzd3VvVnNvT2N4Mi9iWU0KLS0tIEdTQndTT2FjbjZLeDNzWjVWQ01Z
            M3hNTDgyL2pBeWUvcGpNVFNxdzJ3TGsKSpzbmkuOp6ylQ5sUNtQ0r71nNdMQIQsV
            qkPQOKGakHCUv9S8vC5TtZYMSo7c/P03eLs7EjEi28zqPgaepegDSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcm12bUZHTXpCcHROdWo4
            MWljS1YyaWVVNFllZUg5am5WZmlTV1J1RGlvCmdqSjdCUzZ2cncyaDN1K0JXeU0v
            NzlwRi9XMnJFM1pRQWdlZzBwbWFIZTgKLS0tIFAybTlxRFJ2ZUdtWnZTYVA5cm9G
            T2tBUDd3OVllL1pieHUrYWJVOExDYTAKZxXqVc+Ou+XT8JOhSv4mAGV6BFJkjHA0
            w3Ghh6uyYfPV9TlTd+xzInrTdZskvQOOp17L7d1+aNAjm+C/BYaN0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x708x83pjj7urp26pncx67fqz8a3htrf0umw7c00pvmxhl6y95lszjgd6r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaVlJaWF6dWd3NEcyZTBQ
            eFdibi9rTWFWb21nQXRrRGtPbXE1OVE1bWxRCkJHYVY2QWhldmpVc0ZZNlJLaER6
            RENVM3pzWndXM25TeEZwVXlqZkkxdkUKLS0tIEt1d1ZWRDNPVytVQ2hvSEd3T215
            N1JwQjdvZTU0dXFhM2VwNDVaSGdoV2sKlPbE8AANh4V6wQFwUzV0KZTEt6Of7Q0b
            67kVjk0lBcOLek4EFpS3ihrM2s6k9j7NDdYee1GoPNGgGIxCcNea7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12yvljlgg94z8qfwyezz6mtmrpldxvfcqwzsuyfekszu296fg6upseeyc0t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUFRPWEE2aFU5dUQxdGhl
            dTNlQkpwazdsSXdRWVdRNnhxYU00SldLQzBvCmdKUWxjUTR5SEJCby9McnRRN0tq
            U3ZXREIrUFdwU2VVMDhoeXU3cC9rc2sKLS0tIDJiQlRUWjc2OGtWR2xPSVBUblQv
            VGVEclZLWjVUUVB0cjNkMW02ZnBxOFEKdmeD6rE+w2LI6MTexV8U4IXkI7oQAA8W
            n884nezOBFbWJo7z112Kil1lcx6Va/n6j881sTgpcd2InC8PTrPrUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10zakwy8z5448vj7ur2h7vn8wfzvt2nxwq4pk4wx6cs34mlg58yasdjhc7l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeTRiM0tEeEgxcUNDM1Q1
            ak53eWVQK28rSG9uU3NzK01SRXFNZENmdVhvCmZWQ05LN2V3SEhPakZ6UE9kL1B3
            Ni9FWkppSGlTaUI3Q1I4ZFRQUzJ3R2sKLS0tIG5EU3IvZkVVeURUdTlpbkdJN2dZ
            VmhWcXo4UHI2MFV6eGFUQm5GS3dBSTQKrui1zqgClg4Vbd7HQGlxLsYjoW+8anIv
            P9EkcN1SyB7bvTgAJDk6cJs2zISsCIsdJMc++O352pIdWf+Q8DAvNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10q5gqw4gwts228ayanvalq7c93peqjdsfqcgevd7qr43u5rhnczs9u2ysj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycVNDajVsSGh0U1ZjYmVG
            QWhFMmZvRVpjUUh2cWVCUVU5YnlnRXFsdW5ZClJOZk5ML1lUWWZiV2FSM3EyZ1Jn
            YWI5UEVzaGhkNjJRRlYyb3h0UEhHSjgKLS0tICtkSUJPaURxQ3VNWHc2REo0ZHpQ
            UXRKYkI4UTFjUW9GeEs4SFJpblBuM0UKTFvvJJ5j0HFScMQwSEJUB2lEP4ruE2Xm
            5igU+vp9zURWrxGRkN4hFA09l/aioHScdqbK5CReGJ9KiYjGI+Sn6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hxynjkmtgcu9lwejchkjfqjp484at589sznqkxk6weucp37p4p7qaj440h
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZVFCVEtleU9tbDg3S2U0
            bGQ2b2IxN0xYaGJHZ2pOODRkYXVFNTlLWERZCmxETmJoYnhnSFFDWWhDU2REbnpo
            L0MzQ0I1OVp1RzlBMzk4czJZWCtmcXcKLS0tIGdLZHEyY1hRSlVVU3FPcFBOWWR0
            TzRSd05jY3hYQXg2MkRESmZ2bjBYQnMKW+0jgsD19JMTegv93snVBbHKU3aOhoEj
            tFWTbryMP7JY8pyopm+9FVfbWh4+5ChVgMC65a6pwgXHvhUyyBWQrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dtf3ahstj5mhzcqf4d2zc54d5dds69ka32dqpmpsskyaz04dtshq9ryxat
    lastmodified: "2026-07-19T19:38:14Z"
    mac: ENC[AES256_GCM,data:49+G6veG0KG5Di6R/Rsn2AUZiGUyGv4doLBMgjV/RokaNwCZ0qIVkGEIjVbh7AebbPFkOBMTVJLBUK/vUn2PqPIcZ4XIuKtn1Ftk+UiN3CjfjfZUg/jGo/gzmtUTSqzWbEV7sYg43v+6r06Y/OUQCpbnMWxZhrzYEhAMl3Nihvs=,iv:CKjP08+9NKbh0ZeItgwF9SVSbCS3mn8oWdRM7V+ZQAU=,tag:vd+ZirfR0yuHZPrcSuhCaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
