prometheus_plex_media_server_exporter_secrets: ENC[AES256_GCM,data:LmX/Zc5vvzyRps3dX7LxAG02wOjynf9NAhhbSlFk4Zg=,iv:XqRrRLJTKWAcyh2ny9zKwAlMcQqxeHmLH8J06bzn80Q=,tag:IPmhy7qc1YElQ8drmYikZg==,type:str]
sops:
    age:
        - recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5V2dRTlJwTVVkUnFNd0NZ
            RlVXT1ozayt3N1lNLzdSNlNsUXVXWnlwTjNRCldVcXNMc2tkUk1IbFZQc3VwVnFV
            SlZ2ajJRVE5pZ2F3YW1TYSsxUWw1YzQKLS0tIElPMWgzMmpGQ3BHcTZuUlVuUmNk
            KzlXUmFLTTVXZmZlMHlXUk56L1hGNjAKJYpvU5lEaTri8oJIcguxhSTvVsHBC0r3
            rQykbMzFlyzqffzBKV6/gdVijTaKmBvEJylwNCAMM++kNvuez+F/QQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxs9kx4nezjunv8a7m9cz07vd5843dxx239elz2wt0ms6u5ls97q9ud6k7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZU5jSTRqTkdBM0JsUUND
            TWVlc1hOT25nUU9jcmFHMjNzZWQ1Y1ZhcHgwCmVDb3JCQmFUTW1hNE03NFJjYmFU
            aHMzZkhONjN0L0R5QkpvWWQwWDY2T0EKLS0tIC9HQjFJS1Y5RHdpOFR6WkZDbmxx
            YzI2b0wxa0M3S1RPUmZlQzdxVW9TQ3MKsBfYDTFtI1o7PNaI9JlCLQgoJ6pfdA8G
            9VFQsgFAciLXh3RMydxv7hcJZDMDa0ePsrtihSjRfOFam7/72P12+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age134vfx7ce3z7fpzqpcm4nlwcav0apm00g95nrrgm2y0m8wa7rvy6s765gl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvS0diMmVTT3FYUlpOMWVz
            NllXK2Q4UDV5aldMVXVrbldKbEt4ang4Y3dNCjhnaXVFMjJFRC9BRU9iOFZQdlRV
            OEQ4aWhPM05vcGp2V0o2MUZLdFh1cFEKLS0tIHR2clBER2I5UC9yWDhOZS9XSnIv
            N1liTjY4aXBoU2dLZnFCNkZUR1h6bzAK+T5ia8UVAqWqWDTkh7av/ZO8rgjKDhTh
            ihLVvqMXX27AVAz5qpzlhFmtOW09D05xN0AgJq74uDtcU7bpKv9ivw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeXU1U0lxU3JMeXhuRlhp
            c08wU0JKWm14VmNnUCt6b1FlN2xORHpHaTFFCmd2RzNqV0ZvZ2E1dzVJTGMvOG5B
            NzlHRUVZVkdUcFlyZVV5bTRQR1Irdm8KLS0tIEVkSW1qMGpsOGxKdi9CeG9KQUZB
            dUZjOStEZ3AyL3RHeXNWNjliZkFOVDQKkUzikZleHQdaRSQhI7Hh7IaQRN24j9FQ
            xFiArL6NWbdYxuNme9D4wzsJZnfcNdxuvrcnWc/K2nObtKL3zrpR6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4U000VUdxamlkQVVUSG9Y
            TTB6Zms5YVJhcnB3Mld4Tyt6RGlpK0prK1E4CnNHcElsWHNZSWYrc0pUUzIwa05S
            eXU0WFhHWWorb2JzaWM5Q1VvVElzeUkKLS0tIHZsMzFQQ0Z2dllDZlJwcmVIR01r
            TmJYRjFOYnNrUldEZzZoNkQ1UGZZRWsKOO89wQEsdh6Gkh/r3eYSLQcnXJr4oNCa
            4Lw6cGA8A/gEprXMEkf28fOdElrOxgQuRmIUyeepVTbzQUUDE1OLBA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMWhlekIvZ0wwVEtWSk43
            WThDY1Z6UjVIUHVUM25Id2lHaGxFZ1V2QlNJCmd1UUlEclpCTFA3RjJ3TGljVGhC
            RTRPZDFMbS9IK1FDVnBmWVdKM000Qk0KLS0tIDhRa01yTVhlUWJZNHFvS2hteHhP
            Vlp2SFFDUVpQRnRNMG9ubDYwNUlzek0K/ZIgbgFfrXGJQoyjK0w8F2RqaL5J0vEB
            qyJqSUEfD8ngrGQG95KkX8qNuYfX6d4Y8vYxaQvmIgloAcJfshvCRQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySzk0ZElBeGE4Tk9Ga1Vh
            VnNrZEpPRXBwcVUrVmFWSm8vb2Fha1VxTUhZCnFqQllIeFdSdTlYMlQyaEYvejA0
            U0YzVWtZY1pwSzRsa3k1WXJaS2F6OGMKLS0tICttVlE2a1RBSmExUmhMcW9FbUFw
            aE1Helo4aHpaUnBNTXp2bDZRdndpODgKa184+43fo8jVn/D0s+blSWjnTvq48ygY
            qyDSCB0BdUN2W31yCQk8mcUMFsqnJ3VUu4ZjM2p067YzqgxXqO3jSA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TjRTeDBCYnBSK2p5WVFP
            dE43VzJvdEkwMSthaE45NXRSVitHbjV0YkNNCjNxZFpqK0Z0YmRGSi9KSVBtaThi
            MkQza0QzUlcxOFh1U1QxUnVIdHgydFEKLS0tIG5QVGw1SHJpbWErWHFmVGRHaXI0
            cDkvM3djOE9EbTlET28rQVJpSlNjWnMKh0v1Zy6MLvHwUbvYiNfnhXVLnL2X2oEU
            eIRlvsgZS6MguJl8Y6DxESacLauhAQA9q1Z3Bo8Nfftmn2fRlMS+6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-26T18:33:42Z"
    mac: ENC[AES256_GCM,data:2mvcyNziG84IO77+Oj7TGWPUtZ6QYgzmEIDIV3drqMnIY6XTic9w7yp0et9MhDpe+zpNtcsy+QfS25s0NjiNWTmxFwfBI5Ing83VhJ3BEGEuJid2ZE5HO3Xyjlo8yndGI+0w6DyhYMadqPQ2OwS7uGIH7Bs/q/+s55DvkBTBDes=,iv:vIQLhH/MPIHHKHcHXj0rqyQOEEfZdMIyKqSjLWgAn/A=,tag:UnjZybyb1DSbjVAW8p5Eeg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
