---
- name: Import tasks
  ansible.builtin.include_tasks: "{{ task_file }}"
  loop:
    - aliases.yml
    - vlans.yml
    - dnsmasq.yml
    - git.yml
    - qemu.yml
    - mdns.yml
    - upnp.yml
    - prometheus-node-exporter.yml
  loop_control:
    loop_var: task_file
