---
- name: Import tasks
  ansible.builtin.include_tasks: "{{ task_file }}"
  loop:
    - aliases.yml
    - vlans.yml
    - dnsmasq.yml
    - git.yml
    - qemu.yml
    - mdns.yml
    - prometheus-node-exporter.yml
    - ddclient.yml
    - acme.yml
    - rules.yml
  loop_control:
    loop_var: task_file
