---
- name: Install os-firewall
  ansibleguy.opnsense.package:
    name: os-firewall
    action: install

- name: Import rules
  ansible.builtin.include_tasks: "{{ rule_file }}"
  loop:
    - rules/lan.yml
    - rules/management.yml
    - rules/homelab.yml
    - rules/iot.yml
    - rules/tailscale.yml
  loop_control:
    loop_var: rule_file
