---
- name: Configure syslog
  oxlorg.opnsense.syslog:
    match_fields: ["target", "port"]
    target: "monitor.e10.camp"
    port: 514
    transport: "udp4"
    level: ["info", "notice", "warn", "err", "crit", "alert", "emerg"]
    description: "[Ansible] rsyslogd on monitor.e10.camp"
    facility:
      - "auth"
      - "authpriv"
      - "console"
      - "cron"
      - "daemon"
      - "ftp"
      - "kern"
      - "lpr"
      - "mail"
      - "news"
      - "ntp"
      - "security"
      - "syslog"
      - "user"
      - "uucp"
    program:
      - "acme.sh"
      - "acmeclient"
      - "audit"
      - "bgpd"
      - "captiveportal"
      - "charon"
      - "configd.py"
      - "ddclient"
      - "dnsmasq"
      - "dpinger"
      - "filterlog"
      - "firewall"
      - "hostapd"
      - "kea-ctrl-agent"
      - "kea-dhcp4"
      - "kea-dhcp6"
      - "lighttpd"
      - "miniupnpd"
      - "monit"
      - "ntp"
      - "ntpd"
      - "ntpdate"
      - "olsrd"
      - "openvpn"
      - "ospfd"
      - "pkg"
      - "pkg-static"
      - "ppp"
      - "routed"
      - "suricata"
      - "unbound"
      - "wireguard"
      - "zebra"
