---
- name: Allow Tailscale to any
  ansibleguy.opnsense.rule:
    interface: opt3
    source_net: opt3
    destination_net: any
    protocol: any
    description: "[Ansible] Tailscale to any rule"
    match_fields: ["description"]

- name: Allow Tailscale IPv6 to any
  ansibleguy.opnsense.rule:
    interface: opt3
    source_net: opt3
    destination_net: any
    protocol: any
    description: "[Ansible] Tailscale IPv6 to any rule"
    ip_protocol: inet6
    match_fields: ["description"]
