satan_unifi_password: ENC[AES256_GCM,data:UzgG1wyF5uIihoRb,iv:olmw8nAb42exsnMVkaqnVV2Hg97USl0pZT+0Z0+hum4=,tag:w5W5TL55tZmLWA8aTdz6RQ==,type:str]
sops:
    age:
        - recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTWVGVTcvWWZSNlovdEFV
            cWRDVGxhaVphSFROYmJjZ2dyVWc2cWlnQlE0CmNudjBvL3NETEIzV3I0ZFlONE5E
            N21EbXEvdElrYVJFa2RtVjQ2UlZVQ00KLS0tIFJzVlU5Kzk4a3hWOGhsYldZZ1BW
            ZHZsbXNIOVFBODRYK2tBQ3IxU29CZzgKhTYBmZcGEbSH0u69TWJQLFmd+Lm1qSsu
            XO61A3N34lUR+/HLpz/qSOmW8/j2/mdHVaSbzqRft4yhKjoeoInrng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age134vfx7ce3z7fpzqpcm4nlwcav0apm00g95nrrgm2y0m8wa7rvy6s765gl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyamErOXp5aGNUajJhdGNw
            ZkkzYzFQVzJ3Yi9SV0RORDZVQWo5ZlRxcnhBClJjK0Z0VTAyRU00N3RrMDNRQ3NH
            bjcxWW9kVVlWbDFiVytEcFhEbUdGTTAKLS0tIGMzaUZFVVZMMWsyTUJtOUxCNk1E
            T0xwbFRGeFhrQk9IRnE3RE5uNndaV2cK9HTkT0p0h3ETSYUFkdN0/OSG2kq6ySFG
            Yh4HPHkGNWltvc/aLH4whdiqRNX+aY109d4rCyYpo3Qp0j6d/oQQcQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVFQ0L3BYTW9hcCt0OHVV
            RVRUWjNFM3FqVXVMTnpiTGNDWE9RV2xuQ0V3ClYzN25XOFFic1A5MFJmV1B6TXd3
            WCs0L09BRlZ3NjhyNjlMclcyS1hESFEKLS0tIEU5aVpEWTlXWGs3ODZYbVEvL1dW
            WEZhaElxaW4rdWRCSURiZ1dnUHJyZ3MKLx+z3AkDl7ild+QdiT35N4gHi0gZLGBx
            h5O17OGJ/OuNamSG1OTtJedWP67RgAhErhrlwd+hgy2W+tplRTcwiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VHA0VEpqNUIxSUhiMGh2
            RkFEVmNYWGxidDFuc01jUFNCa2xDazFvTW5vCmN1eTdKaVErQ0NIdThpWUkxTHR1
            QXZlY3kya3NOMytZZDczSGZQQmFVYWcKLS0tIHgyY3JNZnpnYjJvQjdISU4yVnpp
            aEVjZmpYWEZXT2luQjFtVVZqWGgyVm8KBwqexTlE9uXllvxWUdza8S2KDvTAEM4d
            V2DwwIdvVAPZbcCrjhaCXcwqy88pTRta5iH8ooowgaKmtw9jblnPEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eGZVMzVvY0s5UThLaXpl
            ZXd2WncrUEJUWS96R3NiOWpybXFXSGc5Wm5FCk1qOUdVeWV1ekQvbXBkdnRBSFlL
            RGdETDB2MTgwT0oyeFkwNzJvWlI2a3cKLS0tIHozSTMyWmZKR3ZLbGFPKzd6OXZ4
            ejFjdCtUUVRKVDkxSVM0WVZFTmdPaW8KBq8nMx4omT5RuSwLC+C1FiJYUcaXBY12
            RUyy2Zc3FkAhT+dqBNO4YXATNHbjSTlRGkwhinaElYTcaadovflDaA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTGVXU3NucWg2alQ3SWJN
            SzZQVElyNGJLTHlzMHpXSHd6c0l6N1k0UzNnCmhpQlcvMittdlhtS29yZ0dDRE1S
            OHFNd2Focm9UZU1kZEI3RnBqc1pIWUEKLS0tIHRlWUNwRXdNMmxlaVRMdGJQVktC
            YzliTVN4Mlg4VVNDakw3b0JKdm5YUXcKaQizoA15np0t882RWLgAv+aojKF8jJw6
            KMlt+6lXCMXTzCpNuuj4a5hZ0pL5mZsQECLteWjInZoLVQidz0CMyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWFZJT1VUak9qSHcvY2Ev
            V202djFrMlRwc0t5dHg2bHRWcjBsdmNVdXdRCjhLczZGVG5id2hSNHJqS1hscHZ1
            WlNuY0c0dkxDaG5mNVA1UHExK3E4a28KLS0tIGhRTjF5WHdSb21Denc3WlhKQkJZ
            bnpyOUFDN3BPQVVEakM1c1E0WDhHU1EKJq/eicQoz0hj8HsUtKt9Ye1/PUbEEU63
            ex3HqgwJ/5XJ2uZ5ucK106FRQ+HnvHN7tzx9VS4084EAThhUAm0PcQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x708x83pjj7urp26pncx67fqz8a3htrf0umw7c00pvmxhl6y95lszjgd6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWFdjK0xXMGVQRDVwZm93
            Q0RpRkhTT2R3NGRFZ1R3ODdQc3RFOFVTWDFBCllzOUl4U0ROYk5EdlFSOHJheDBX
            K3JYNjgzbWM2Z25rSHpRK1FJdlR4b00KLS0tIFBRU01nZnZpMmM2bFRJbWxpSFRG
            aEM4ajkrakw5OGtEdVJMYll0R2w0LzAK0XzvwPlGX7//uXYyzv3K8PAxfzoUqkEd
            MDqSZkS3piTYQ6ES8bD4uJspPvR4NH1XMlGkul7Mo6VTVgzmFjtoMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T02:53:02Z"
    mac: ENC[AES256_GCM,data:C8LQjnu/iabbR0LTej2Yhk1vSzM9NTei5zN7ZP8SLjcH3Wo96wgVPmoIul0cE4JQ93h3NVqojv9L5xGUD0CXLi1BTdzKTGfvnvuABUB8fiiOtLwyqxOit3n3yt7ya4w6noRT4yRNbHuBfCew0n6iYVi0xp4nhCR2cObqRtkhpBQ=,iv:it8udoLlguuMwg4o4zX8VEAjOAKPOycxgmJpeT3F0V8=,tag:ZyiYPB4MAV/X/rAV46JLBg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
