satan_unifi_password: ENC[AES256_GCM,data:UzgG1wyF5uIihoRb,iv:olmw8nAb42exsnMVkaqnVV2Hg97USl0pZT+0Z0+hum4=,tag:w5W5TL55tZmLWA8aTdz6RQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdGxYMll2RGE2bVQvbCtn
            T2UvUWZ2WFhjVnJKZ1YwaC9VVWJ5Wk1iM2lBCkl4NUpBcXJET3Raa2tUanluWEhi
            NS9OY2J0cmVDaDNOQjhMOUZHNkFMRlUKLS0tIHc5QXZEVmZBOUtmY2liRzB6VG9N
            MlJXeHlaWXc1UDVyaHFLQ1R3K2QvckkKOxWSm+QEsOFoW0BICJPhRzbHzfRJFKyi
            /zp6MeftA2qcLB41lpfsywoU7OzcRCdVH3E02bhXaSeoAGgFQQi47w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSS3BrUFlXRnVvSU4ycXNt
            amkzdHpmb2oraXY4UXJxL3MwMnJERjlaUzNNCjBSR0ZSdnVWMjR4cUIxb092dDF3
            MXFLS2pvY0MrdzRINjZsUExmSFcyeUEKLS0tIEFobWUzUGZNSER6VWIreFRWQWR5
            YnRabklkMGJXQWxPRGc0bnpJRkJ5QkUKwS/8Zy9pwRsaU9bXGt+wVzjx6AtEBpHS
            NmyODA5StzeklpcmxVY/demzkkASPIa004nrl7NsoVxPU2J5yz3UwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g22ghnrdg858yv6w2ux8hgntj8gkdyjn28axdkmzyx38d4vx6geqj4px9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVThtK0htMStmODFDYkhz
            WlYrRGNkMy8rdE9kcnF5bkUxUGtQSXViT1FzCkNDMUNCUy9xSW0vd3IybGdmMWtH
            MjNlTFBQc1cwM3l4YS9kd2l1TkQzOXMKLS0tIFdPQ0VQY0Fsd2VMM0JmdHRld2Nm
            K005NlNMY3M2aEx0Mk0vRlVleVlkbU0KQJtBghJUyPGIZ2eLRtBLFJbwgXsMe/aW
            lAXJBgyKcLDF1XeMvf+0l+wnC0lvV33k7DytYffTQEo5mwf6PZMeqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbU1zOXFiMjkvOGE5OUhY
            WjR4eks2NXl1NFVlZWY4K1NKSzh1VERFaUhFCk1kNnNFdmpGMnFUV1VrU1pJTThu
            WWZ4ZHdHeDM5disyM1FqYmdBS0I4V3cKLS0tICtxOUhmZG8xajN6SjRNUTQwWmZj
            U0szTmNqWDluSGZpa2tWbmFuZUFHb00K+U3gdzRm00iuFuHIrsF2wGG5A/zH3WMv
            OpZP6Lv5GugwogYSgBDi2yVLOBdfE5QzScvEWczFTkb8x7eEE3CgDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3K3pBZ00xOTRNTkxxTFdm
            R2tkYzNtQzNtcFZJRXR4MS9obklUNGJpZ2dVCnZKVmNkQkZobmJvV3NUZmY5OWl1
            eG45cGRZVzZrNFUzMlhhU3cyZmpsRmsKLS0tIHYxWjhhb1JGVjNtU3VGU00zM0JJ
            L0htT3B5UWFuWmVkVlRteHhrVXBCVW8KK6OYwtzkXlxBqRxybWO6SL5pSDvyzt44
            6IHuzKszxhfNCIP9367bKVE31Dn/CrYdpNfc6yI6EPe2AjxBwIoxxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6U1BYUjlZOWdNdEVZRUk4
            d1E1ZXFHcSs2V3ZyM2dDV3Nka0VSRXZscGxvCmxaUDQvWWFldEdMVXBrcnVYZkoz
            VnBjRzBDZUlUZWpJRkdIcVA5UFFBSjgKLS0tIHIvamxiRUlWMklSVEgzZWErTktB
            OGlXdVNlaVA1YlFNR1d6NndydmVac3MKQhVnvyLBRIcPpTZkNqTN2Fwe32xJafbW
            qqWI4wxIySItEK8jYSIa28gn4BTWpAFhFWNcLXUbWU5WFSbyp2l9nA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZW9hdXU3QjZMZjhQTzlZ
            UTVmTU9IV0Z4YkJITHZTcnpHeUdZWTlGSjFZCm8raEZ5S2w1bVMyYTI3YTE4WFZR
            b3RVand0TGVUamdiSWYzaUpSSDJjNW8KLS0tIFdXazVvQmM3VkcxWDIrMG1SK3Zx
            anNaOE5Ec2dzcXhqYmQvQTBJclNlYUEK1aVa3KbaE0/Cjq7vRu12iX04i4pwzIgo
            9UAkSEJC0C3ldZGgo92Aa6K/Zs+7hC2qiBXsFLMjbJOabAgvIgES3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM0JPUWFoN2g0TFNCRWE2
            Znh6cWp4SmU1djdqaWxmQksxWVpJWk84LzNRCnllQWszUWJpVHVzUHBKUTUyY1Za
            YzZzZGxSdnVFcjRYdTduVHBJaG93UG8KLS0tIFBaMjZraDEzT0psY0QySGN3VFRR
            Mk9EbGxxSkttb0Z5Wk4xN0FORDdqd0UKJ40Av+T3zh6dFL1Ph+3vd4UhcXBex61u
            w0VSTiOgPkBLv8vrBHazXsfmE2tfG948pdOGg36YCe00wqAEHcbuZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x708x83pjj7urp26pncx67fqz8a3htrf0umw7c00pvmxhl6y95lszjgd6r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSjZSR3RrR3IwU0VwSGky
            c0pjakJWcWY5Tk5ISWdYVGIyUVpuWjFZb0gwCmh6OVFkY3dRRk1KN0N2a3IwSXFj
            VjVoZlIrU0RNUGpLZ3hKeG5CK1RHbmsKLS0tIEZmaFBPUnVsZ2JDcUwrSUVSUzVk
            ZWpOcHRTZEFQWUJNVEFscG0zUlNNdkkKIVbqdZAdGDxuSQkCAWVXEcgIC32I6chW
            NR5/3PG97N0BiUUdEut/uV3KmhA4Gof/M7/E461n0reDMc6lnoa9Tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12yvljlgg94z8qfwyezz6mtmrpldxvfcqwzsuyfekszu296fg6upseeyc0t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdDNEWFBpckxsVFZFRnNJ
            d0N4MnJRWlZOUjZyS0FZQ1drT0FGb1FhMW1NCjFvYUNseWFITmt2NGZkU290UlBI
            R3JsMjFpejRvdkMxWXgwVTNCSG16L0UKLS0tIHVGOVNaaE8xa2hIU3pWQ1hWQURX
            cHpWeFBaODhBYUR2bm1MR3dnUzRyVlEKwBLJ6zLQGsfJppQCdG+S2LP2PYq/imbQ
            8RunrJsSbnBxHqfDWQtvPnIFHGdi1j9Siw4Mvj+bfmrL5e6PfWbrhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15fqamv69dmkds8twydjtguj7s3lunjl8t6k56783chslplex2upqzn68xr
    lastmodified: "2025-10-01T02:53:02Z"
    mac: ENC[AES256_GCM,data:C8LQjnu/iabbR0LTej2Yhk1vSzM9NTei5zN7ZP8SLjcH3Wo96wgVPmoIul0cE4JQ93h3NVqojv9L5xGUD0CXLi1BTdzKTGfvnvuABUB8fiiOtLwyqxOit3n3yt7ya4w6noRT4yRNbHuBfCew0n6iYVi0xp4nhCR2cObqRtkhpBQ=,iv:it8udoLlguuMwg4o4zX8VEAjOAKPOycxgmJpeT3F0V8=,tag:ZyiYPB4MAV/X/rAV46JLBg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
