satan_unifi_password: ENC[AES256_GCM,data:UzgG1wyF5uIihoRb,iv:olmw8nAb42exsnMVkaqnVV2Hg97USl0pZT+0Z0+hum4=,tag:w5W5TL55tZmLWA8aTdz6RQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZWt1aFp0U3BWNmxoRVB6
            Z0tNOTMvVGRTdmxWOElWc3pHakxHb0FGaVVnCkRmNUhGcEVGWGlyTzNXZ3hwQy9Q
            amxPeHcveE1iYWZDS2Z4K1NUcTByMlUKLS0tIEY0NDY5R2ZiUURsVDdULzNqRTJq
            MDZrTCt1Q2t5TUpwNExXVWpBakUxSkkKkGKWrJersQXyU265wT6M7LoyPOpzO+Wc
            vP2GyDljXprGxLkKAUv7gSXo98R+FZLcKP8JXrGynUYG7wRphWFXhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSFVqODl0WjlndjkreEt3
            Zlh0WjFvdVJKamFvTWtVbjZFRjZ6bzFHQTJnCm5NMDBoZ3hUNkpWbm5PT0l6bVFQ
            YWZhWENFMTBNUzFpbHg3YmVTMTRtek0KLS0tIGYranZvcjl4bDZNbjZpZmZuN3o4
            MnU3MktDOUJrTG41K051NUszLytsdVEKwJd4gWB/CoKwueE7ZSoSQxjLmyyKpBOb
            SqPX9Ta+RTXGVCxtEWRYGK0esywa/EF+Y5IRVtSS9Fqrn+Me5bTvOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g22ghnrdg858yv6w2ux8hgntj8gkdyjn28axdkmzyx38d4vx6geqj4px9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SUxoa1dPN0g2dlNQaFFN
            bFpyZWw5ZzNLdjFXVGtBMWdYMHpzQWtOempjCjZqazEzc0tMMHI5cTNzVWlQckRt
            U25ueXE0S1ppeUlCeHQvWlBBVW5QQW8KLS0tIGtDZjVFYVNVYmhob0pEandqVXFx
            K1dVOGJWRXFneXBlZkNSU1I0KzNIK0kKulbYAOlbSckdW5xlvZs5m54T56cylw4i
            qwChyEQEi+9Rttk/LHmaGfLSkl0zMczv7r0CBcVMWXu/fNgNOp4/8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aXBLL0hyY0tFRFM3ZkZa
            ZUYzK1YzY0lVTGFCSnVlNENpMzRXYzJNcEdzCjAxd21taW53KzBLRUljR1cxVjZ1
            UUdNeUF0TGRraThRQVAxbW11R0NRcjAKLS0tIE1QeitPSWZNK3ExdlBaMkRyelhH
            THRuRDhSdm0vWTlJQnZ0RVBnYnpuS3MKR1oPK6dgfMF1eXAqCAWoFEiyD6WZPlni
            ZophEeVY9s027PfPE31beGD14WIiJEcu6LTBtfjOXM4fAsTT97inbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTDByN0kyZzJ2SVJzL0Ex
            Zk5rZjJwZm8wci90TWE3aWpFL0dnSHU3b2g0Ck0zZ29ac2dodWhhNUp3Wk9xNTN3
            MkhucmxGdG4zVmtQWkJKTlVjaEp2MlEKLS0tIHY5TkdKSDRkWVVXRWVnZTE5d0ty
            blRpd0trd0tlYWwvSm9kbENEYjk3Y2cKWbTLvwYAQqJR61uHrb7WcrMhui7VevjV
            sGrgaSkYbIuarguRp3KH1zbiad+eMyLpIIcnXBKymSlmXKMxPo2XoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL1RxbjQ1UDAxR2ZteUlF
            M3JWdnlMVFJsQ2t0TitpbkF2b001ZjBCZlJzCm4yQ0QyNkwwSmxpd2VEaUhkMXdM
            SFU2SS80K3VYajZCcHpxNjQ0MlZpekEKLS0tIHBVcm80enV3Rm9tOU43ZWJMSGM4
            M3NoSDRvclROMTg1RjMvSkxCTGJzVkEK0ep8IuUxrwB8/qQdySLcnzUgIiQ/1/M8
            OYHll3Jbo7RQ0fbko4ofqpjVp5liuj5qJ6uETiAEIKjECNaeQomkKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZVEvSVl0Zzd0eFROZElh
            QS9qV1d3Syt2TU02Yy8zdlhpYmRIbmtRV1Y0Cm1LdjZ5YUVUS0J1RE45dENwQ3Jq
            MmxVMGE2TzRRY1lxQk5lSEdQK2JQUkUKLS0tIDlrRThsTURYNDR6TlRhSFVkVXoy
            ZG83ZkIyVFFSVDVOZGpZS2NnVW11S0UKb8HutDFRL4dqkHHew2oRvEgicM1e68nA
            AkSJm/yyEd0OgZYDfaFbxkNQPQGZwNNkvT0j+4UGscXN9Mfk+vGQ4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzc001VElBTW9nSG1Kc2F0
            cFVQL3ArZlIyRzNsRytGUE1nR0xocm1sdndVCkZ0aWIyREhvWktwaGVsZVVHWXRM
            THI5d0xMYUZabVByM3M0R3Q1ZTNiajAKLS0tIEVDcFJKWTJxSFdXenpOdGNoMDBv
            YnJxTlNyL1cyNmdNWnlFSGUvVCt6S3cKRqPQis8zZyMj/q3YczLa1P0QGF+SiKv9
            WV1CuQ7TjPaGFs2uf//Qhw0wkC+0WtjaFYYzhZQfB7pmW975jebDVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x708x83pjj7urp26pncx67fqz8a3htrf0umw7c00pvmxhl6y95lszjgd6r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSWl1SytPZ2ZtRkE1SjB4
            RWMzQXhyT3ozRzV5T21kN0ZKM3dnalZOVUNBCm1TTld2MHJCNHNGelIxUUNqNEhG
            NkNvbnVTQ2VtaG0xTUJjOU5rM0kwRGMKLS0tIGh1bmpjRi9qVGgwUzMvTzNoUm1o
            YTdMNTJBNXdGbTZLNG9MRHhRbTNDYjQK2bNRxR9sT6W7y4Pn//v414HRy2it7LXr
            rD1jDj9BiHGYety5A+MB4w5iZlZJjfV8bTwuQVNpFqBaNsKA0PpdNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12yvljlgg94z8qfwyezz6mtmrpldxvfcqwzsuyfekszu296fg6upseeyc0t
    lastmodified: "2025-10-01T02:53:02Z"
    mac: ENC[AES256_GCM,data:C8LQjnu/iabbR0LTej2Yhk1vSzM9NTei5zN7ZP8SLjcH3Wo96wgVPmoIul0cE4JQ93h3NVqojv9L5xGUD0CXLi1BTdzKTGfvnvuABUB8fiiOtLwyqxOit3n3yt7ya4w6noRT4yRNbHuBfCew0n6iYVi0xp4nhCR2cObqRtkhpBQ=,iv:it8udoLlguuMwg4o4zX8VEAjOAKPOycxgmJpeT3F0V8=,tag:ZyiYPB4MAV/X/rAV46JLBg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
