bazarr_api_key: ENC[AES256_GCM,data:DAP4n6KPjNA6Pzz5rRHSRhCE61FB4GseLYfPz46aNA0=,iv:pTh2hb8/zv9adOjhLeu/f9M7v6fy2Zb5bM4tG3qDFqI=,tag:VjZgvTOeXKxBxksHS3CgAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnR0M0N013WUs2aDBBMEZT
            OXRwQnBzZTBrNXlmcFUwSWxtdkUvV2hLUlE0Cm51dlQwRGlRRzc3OEJyTU5WWC8x
            ZEN0N3lGbmMyT1l0d095Zm9aLy91NkUKLS0tIDgwNFZnUW1kQjRxY0d0MlAxdTdR
            dlZieDJEZGFSRVBldzh0dldaSXUxK28KF0Ug5mjq1WiJuAF56TUV+DnF3NLR8Yho
            Dxg+zx+FiAh+6aDUcuq71B5jN45JGRk+GLQvgo0oTTDtRvQZ3AvFKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17lsd78hka8rmuvmmx6d03cqjl2h55lsvrnzdfq0ge4acujf6nffswdwvr0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOTBJRWN2RWxnZVdhZTBJ
            MGFnQ3hLTlZHR0Roc1FOYmQ4c2hSVGxkNGg4Cjkrbjg2Q280Uk8rRnFWd2NCNjVq
            SEZjT0Q4QnE4VEIyY2IvSXZISUF5Y1EKLS0tIHIzMUJUc3lCU1k2ZW90MXBRbkcv
            aDFSeXNEMjQraExuUjc1N1orRFExMVEKXQ1L/d08hrRGTqTXjQJ/SPtlB2MRsrHF
            F0WXyN0N2I9tvMAhwDx2nqtnWApLxEShX2BPosA6lPxl8WKeRKDwRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jmr8lvn5wmxv6w0lk3vapawljnqfvws095ale94mthcgxueza9sscqq3h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dnl6RFYrakFJa3V0Y1gy
            NkcyZVQ4MXVOVG0zTWtQUEVaR3JOUEJHRjN3Ck02ZGE0enIrUmswN0JZeUhpYVg1
            QWVlajdFeVVodjNNNXJSLytRM3Zwa0EKLS0tIDBaVDdNMnJJQkY5ampHaVdWN3Bu
            SVVYbmh4Q3plY3lrRkNYNGVQU1A4elkKjIu8dSUKsW07NFPmEX6loYtIXHh08L+P
            /mkOzW9zZ3UZZpr+j185457VWTb1aGOCY1CAwCkI2FtQskjnr0W+yQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k5nzxq4ej2u9ls97c2dhlz96j2vghv0assz5g0p4npzyc8c8fqlqld72hg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETEU3QlQxUWVaSDRhOEQz
            SkNsejU3MWlzMWpKTG1aZDRKVmpjWUVYMjJzCnNqMFAyd2Vwc0lUZUxocTJwdnZw
            NEhzQnd3cWJmM0YwSGloV0ZxZElra0UKLS0tIGRza2FSeEczMUE2V09LaVJINitM
            QW9WaDZidUUrTUtsbEpYdkxVS1ppa1UKBN9vzMCUPdz8Ojem8zP4TwO1h7IJfq+z
            uaRbUPTLsIQ3t5jpoAJW9YD5NeYLK1PRckHsNZmCdVqDXoeu4Fp+fA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gkzp905yqkla54l52m4xkqtxpn0sndkx0vh6qqa8d2tu29x8f35q354gpe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKR2lySG5OVHMrRElWY0Np
            c1FSYkFLZVNNTW0yejZxbmowWFd6SmJYOXpzCkpIb29UT3ZxaXBlaEdvM2hKUGI3
            SEZmSnRhb2ZjRnE3RENJcUNuRGF1cTQKLS0tIGwxMCt6S3lKQTl6QU5ZYWRiK2dj
            aTVrVTkvWHp6b3hFcmxHampDU3FkWDQK6AFiTAQlJEWZfixqbp174mLpACNOkX71
            JDe4/L3utUUnl3J549TLGMbLn7zJieHkT0kYi0EDaKq3yUpz7mvyWA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c4d93hmawmx8nt8g2sjrxcngfl7qx7y6vwxpqqg7grrkhjen6fvstljgg9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYlBNdjYxejgySGc0T09j
            alQ3N0hpeTlSU3A3ZURiUmN3RTJMSkVkZmc4CmFjRUpuZHVuQm91VzZac1BNQmpy
            QVRMSU8wbllXUVgxb01KVlhvRnBPTVUKLS0tIElBeUttekZUY2loWHNuV2tadnda
            aUxySnphc201cWFyYk9vd3I4T0FURFEK8u2XjP05sMdGpO1YPVdIbIqRudPiVYmw
            A7tYs/pJ9df9DOgM+pNycYLSvCvo8v7NP4VNIy0gnsgZzC8BBDqJrA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15jjykch8km3l8atssu0n9us6d2xg58z0ds9s0djtdh9l954sud5szqxv29
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMzd1ei9TdGRrUHlpQVhK
            N1F1OUxiUnFFeDdsc3VmQXZOeVQ4QkN5b2w4CndqY2hZWXBMMVBJWWJpdTFmZzJ1
            RGFPQ3JUYlBQSVhlSndwVTVDYk1UTGcKLS0tIGZycFNhMWJLa2FaZ2wySkdvV2Vu
            UVcvaWd1WkxzUVhsNWM2dWcxWURyOHMKgefciFYkttR9pZm8F8E0gy3czurHWtp0
            u+31rOqyqmRl9M7c+Spj5Df4e1hicqQmjRaw20tjpXhAYNS3CyKXRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jhawn266e3wr6rx0lndkl9a47ewtk6jgh35d2582uu2l7dtn4tqdqc29c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadFhKaURDaG1KZ21xRHRP
            VGQwYy9iT1FzL2F4V1lvZFl6U0RRZmRFa25JCjJWYWNMVW9tY0NEcXQ5UFM0cnFF
            NGFic3VvSkY1RHhqdlA2NHhmeVIrS0kKLS0tIFpucE9hMkpkZFJ5SVV6ZmVtL1Ar
            alpmTGc0VUEyTVRzS2RiQm9YNlNyRVEK7jQtywf+Us3jdpGlGXbcbQF439BWpe9/
            aLTXnVz4Lb9ssPm9YBVZr5McRYCdwr1MjIrTNHVQuLh/CejvOFSAZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a4r3d5m0eu94vwsrse83k09fgclcfmthkz93p6h0m5vqyptq2yxswptzjf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQlNFS0luVm9MSEJtcWMx
            R3lSQmg0NmE0RGxDOVpEb1JnT0VZSG53WldjCk02d0NQcEFEUU1YVEFSSVBlMjBS
            a1prdUhzQlpHSDlEcWsyeWUzdXY5T1kKLS0tICtVdE43eGI4V2lMallwNXlVS2Nw
            Z2hNMUc0RE1ZbVFIZnJ3ZEVpTEtwT1EKlXzX2liS1tchkEd6z9vZwXiqTNypkDtR
            drcm6fHc56J4I0R6pvg7jfOCwJ/YPGkmhlkGsYmVr0Ns0Rr5Sf6+iQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12yvljlgg94z8qfwyezz6mtmrpldxvfcqwzsuyfekszu296fg6upseeyc0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESnRrSGNaa040OW5hS1p1
            MjlWWjQxL3dmc0JQQ2xUUkR4dS9Na3JWTW5jCmRFbGVLSWt5MXNKb04rVk5LcTEy
            MkhaMW9abjN3b2FtamZzVXIvdzV3dG8KLS0tIE5ieVFlblptS2ZNSXUyWjNJUWw5
            V1hKTmJaVnNxU3V5Qks0Sm9xNmJEZncKjeHcXI+EcjxuYnPv1Yj3lzh3XN0q7NFy
            j7AHSVDx+1CrULRAvfqNP1QulcdAX+fjchwlzgtWrdpXwoPrQ20FFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-26T04:02:51Z"
    mac: ENC[AES256_GCM,data:ZDewG+kWslVl1eipylhVhKJ9wYya/kqMIFc7m7ak1PNeKzbpL/rPTiKTwpuBFebDzuuaeUSBoLUTw25TBwr5z0DfcmkeyVpXEY4CDVK1d9NH+epOEmgJB5tXyHzz0F7i+orZCZhkbZyH5EXnbvuOI+OIdg30C1jBqjb3pJOVY2g=,iv:bW3ZNlu7WUvlE1uMbOx9nNaCz7g91PV1ldbb6xI7UpY=,tag:OUKxpkMKGivL4xIyCniGog==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
